project_id = "aokkyrgaqjarhlywhjju"

[functions.backup-signed-urls]
verify_jwt = false

[functions.crm-blip-ingest]
verify_jwt = false

[functions.rrtask-poll-status]
verify_jwt = false

[functions.rrtask-webhook]
verify_jwt = false


[functions.rr-sync]
verify_jwt = false
