import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "pt-BR" | "en" | "es" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  "pt-BR": {
    // Sistema
    "system.title": "Sistema Huggs",
    "loading": "Carregando...",

    // Navegação geral
    "nav.dashboard": "Dashboard",
    "nav.notifications": "Notificações",
    "nav.audit": "Auditoria",
    "nav.install_app": "Instalar App",
    "nav.settings": "Configurações",
    "nav.logout": "Sair",
    "nav.connected": "Conectado",
    "nav.all_modules": "Todos os Módulos",
    "nav.n_modules": "módulos",

    // Idioma
    "lang.label": "Idioma",
    "lang.pt-BR": "Português (BR)",
    "lang.en": "English",
    "lang.es": "Español",
    "lang.ar": "العربية",

    // Offline
    "offline.message": "Você está offline. Algumas funcionalidades podem estar limitadas. Os dados serão sincronizados quando você voltar online.",
    "offline.poor": "Conexão instável detectada. O aplicativo tentará reconectar automaticamente se houver falhas.",

    // Módulos (sidebar headers)
    "module.prospects": "Prospects",
    "module.financeiro": "Financeiro",
    "module.marketing": "Marketing",
    "module.trade": "Trade Marketing",
    "module.fabrica": "Fábrica",
    "module.comercial": "Comercial",
    "module.eventos": "Eventos",
    "module.departamentos": "Departamentos",
    "module.precos": "Tabelas de Preços",

    // Prospects submenus
    "prospects.overview": "Visão Geral",
    "prospects.list": "Lista de Prospects",
    "prospects.kanban": "Kanban",
    "prospects.activities": "Atividades",
    "prospects.tasks": "Tarefas",
    "prospects.demands": "Central de Demandas",
    "prospects.title": "Prospects",
    "prospects.registered": "prospects cadastrados",
    "prospects.new": "Novo Prospect",
    "prospects.ai": "IA",
    "prospects.search": "Buscar por nome, email, telefone...",
    "prospects.filter_status": "Filtrar por status",
    "prospects.all_status": "Todos os Status",
    "prospects.update_list": "Atualizar Lista",
    "prospects.none_found": "Nenhum prospect encontrado",
    "prospects.loading_list": "Carregando prospects...",

    // Status
    "status.novo": "Novo",
    "status.em_contato": "Em Contato",
    "status.proposta_enviada": "Proposta",
    "status.negociacao": "Negociação",
    "status.ganho": "Ganho",
    "status.perdido": "Perdido",

    // Labels comuns
    "label.email": "Email",
    "label.phone": "Telefone",
    "label.seller": "Vendedor",

    // Financeiro submenus
    "financeiro.overview": "Visão Geral",
    "financeiro.consolidated": "Dashboard Consolidado",
    "financeiro.dre": "DRE Analítico",
    "financeiro.departments": "Visão por Departamento",
    "financeiro.trade_budget": "Gestão de Verbas",
    "financeiro.payments_center": "Central de Pagamentos",
    "financeiro.dept_approvals": "Aprovações Depts",
    "financeiro.payables": "Contas a Pagar",
    "financeiro.receivables": "Contas a Receber",
    "financeiro.cashflow": "Fluxo de Caixa",
    "financeiro.bank_balances": "Saldos Bancários",
    "financeiro.chart_accounts": "Plano de Contas",
    "financeiro.classify_bank": "Classificar Banco",

    // Trade submenus
    "trade.admin": "Administrativo",
    "trade.my_team": "Minha Equipe",
    "trade.pdvs": "PDVs",
    "trade.visits": "Visitas",
    "trade.sellout": "Sell Out",
    "trade.shelf": "Medição Prateleiras",
    "trade.brands": "Nossas Marcas",
    "trade.photos": "Fotos",
    "trade.ideal_photos": "Fotos Ideais",
    "trade.audit": "Auditoria Gôndola",
    "trade.competitive": "Análise Competitiva",
    "trade.rewards": "Premiações",
    "trade.whatsapp": "WhatsApp",
    "trade.ai_insights": "Insights IA",

    // Marketing submenus
    "marketing.dashboards": "Dashboards & IA",
    "marketing.overview": "Visão Geral",

    // Fábrica groups
    "fabrica.dashboard": "Dashboard",
    "fabrica.entry": "Entrada",
    "fabrica.nfe": "Recebimento NF-e",
    "fabrica.raw_materials": "Matérias-Primas",
    "fabrica.production": "Produção",
    "fabrica.formulas": "Fórmulas (BOM)",
    "fabrica.planning": "Planejamento MRP",
    "fabrica.orders": "Ordens de Produção",
    "fabrica.tracking": "Apontamentos",
    "fabrica.quality": "Qualidade",
    "fabrica.stops": "Paradas",
    "fabrica.resources": "Recursos",
    "fabrica.machines": "Máquinas",
    "fabrica.operators": "Operadores",
    "fabrica.fiscal": "Fiscal",
    "fabrica.tax_table": "Tabela de Impostos",
    "fabrica.output": "Saída",
    "fabrica.finished": "Produtos Acabados",
    "fabrica.review": "Revisão de Fichas",
    "fabrica.tools": "Ferramentas",
    "fabrica.agent": "Agente Huggs",
    "fabrica.qa_agent": "Agente de QA",

    // Comercial submenus
    "comercial.dashboard": "Dashboard",
    "comercial.launches": "Calendário de Lançamentos",
    "comercial.ibge": "Dados IBGE",
    "comercial.mining": "Mineração de Leads",
    "comercial.reactivation": "Reativação",
    "comercial.municipalities": "Municípios",
    "comercial.whitespace": "Whitespace",

    // Eventos submenus
    "eventos.events": "Eventos",
    "eventos.dashboard": "Dashboard",

    // Preços submenus
    "precos.dashboard": "Dashboard",
    "precos.matrix": "Matriz Comparativa",
    "precos.manage": "Gerenciar Tabelas",
    "precos.approval": "Aprovação",
    "precos.client_portal": "Portal Cliente",
    "precos.access_control": "Controle de Acesso",

    // Departamentos submenus
    "dept.expenses": "Despesas",
    "dept.dashboard": "Dashboard",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Visão geral do seu CRM",
    "dashboard.ai_insights": "Insights de IA",
    "dashboard.activities_30d": "Atividades - Últimos 30 Dias",
    "dashboard.activities_timeline": "Linha do tempo de atividades registradas",
    "dashboard.activities_label": "Atividades",

    // Dashboard widgets
    "widget.total_prospects": "Total de Prospects",
    "widget.prospects_registered": "Prospects cadastrados",
    "widget.in_negotiation": "Em Negociação",
    "widget.prospects_negotiation": "Prospects em negociação",
    "widget.activities_today": "Atividades Hoje",
    "widget.activities_registered": "Atividades registradas",

    // Módulos rápidos
    "quick.prospects": "Módulo de Prospects",
    "quick.prospects_desc": "Gestão completa de prospects e pipeline",
    "quick.trade": "Módulo de Trade Marketing",
    "quick.trade_desc": "Monitoramento de PDVs e performance",
    "quick.financeiro": "Módulo Financeiro",
    "quick.financeiro_desc": "Gestão de contas e fluxo de caixa",
    "quick.fabrica": "Módulo Fábrica",
    "quick.fabrica_desc": "Produção, fórmulas e qualidade",

    // Ações comuns
    "action.save": "Salvar",
    "action.cancel": "Cancelar",
    "action.delete": "Excluir",
    "action.edit": "Editar",
    "action.search": "Buscar",
    "action.filter": "Filtrar",
    "action.export": "Exportar",
    "action.refresh": "Atualizar",
    "action.close": "Fechar",
    "action.confirm": "Confirmar",
    "action.back": "Voltar",
    "action.next": "Próximo",

    // Logout
    "logout.title": "Logout realizado",
    "logout.description": "Até logo!",
  },
  en: {
    "system.title": "Huggs System",
    "loading": "Loading...",
    "nav.dashboard": "Dashboard",
    "nav.notifications": "Notifications",
    "nav.audit": "Audit",
    "nav.install_app": "Install App",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    "nav.connected": "Connected",
    "nav.all_modules": "All Modules",
    "nav.n_modules": "modules",
    "lang.label": "Language",
    "lang.pt-BR": "Português (BR)",
    "lang.en": "English",
    "lang.es": "Español",
    "lang.ar": "العربية",
    "offline.message": "You are offline. Some features may be limited. Data will sync when you're back online.",
    "offline.poor": "Unstable connection detected. The app will try to reconnect automatically.",

    "module.prospects": "Prospects",
    "module.financeiro": "Finance",
    "module.marketing": "Marketing",
    "module.trade": "Trade Marketing",
    "module.fabrica": "Factory",
    "module.comercial": "Commercial",
    "module.eventos": "Events",
    "module.departamentos": "Departments",
    "module.precos": "Price Tables",

    "prospects.overview": "Overview",
    "prospects.list": "Prospect List",
    "prospects.kanban": "Kanban",
    "prospects.activities": "Activities",
    "prospects.tasks": "Tasks",
    "prospects.demands": "Demand Center",
    "prospects.title": "Prospects",
    "prospects.registered": "registered prospects",
    "prospects.new": "New Prospect",
    "prospects.ai": "AI",
    "prospects.search": "Search by name, email, phone...",
    "prospects.filter_status": "Filter by status",
    "prospects.all_status": "All Statuses",
    "prospects.update_list": "Refresh List",
    "prospects.none_found": "No prospects found",
    "prospects.loading_list": "Loading prospects...",

    "status.novo": "New",
    "status.em_contato": "In Contact",
    "status.proposta_enviada": "Proposal",
    "status.negociacao": "Negotiation",
    "status.ganho": "Won",
    "status.perdido": "Lost",

    "label.email": "Email",
    "label.phone": "Phone",
    "label.seller": "Seller",

    "financeiro.overview": "Overview",
    "financeiro.consolidated": "Consolidated Dashboard",
    "financeiro.dre": "Analytical P&L",
    "financeiro.departments": "Department View",
    "financeiro.trade_budget": "Budget Management",
    "financeiro.payments_center": "Payment Center",
    "financeiro.dept_approvals": "Dept. Approvals",
    "financeiro.payables": "Accounts Payable",
    "financeiro.receivables": "Accounts Receivable",
    "financeiro.cashflow": "Cash Flow",
    "financeiro.bank_balances": "Bank Balances",
    "financeiro.chart_accounts": "Chart of Accounts",
    "financeiro.classify_bank": "Bank Classification",

    "trade.admin": "Administrative",
    "trade.my_team": "My Team",
    "trade.pdvs": "Stores",
    "trade.visits": "Visits",
    "trade.sellout": "Sell Out",
    "trade.shelf": "Shelf Measurement",
    "trade.brands": "Our Brands",
    "trade.photos": "Photos",
    "trade.ideal_photos": "Ideal Photos",
    "trade.audit": "Shelf Audit",
    "trade.competitive": "Competitive Analysis",
    "trade.rewards": "Rewards",
    "trade.whatsapp": "WhatsApp",
    "trade.ai_insights": "AI Insights",

    "marketing.dashboards": "Dashboards & AI",
    "marketing.overview": "Overview",

    "fabrica.dashboard": "Dashboard",
    "fabrica.entry": "Receiving",
    "fabrica.nfe": "NF-e Receipt",
    "fabrica.raw_materials": "Raw Materials",
    "fabrica.production": "Production",
    "fabrica.formulas": "Formulas (BOM)",
    "fabrica.planning": "MRP Planning",
    "fabrica.orders": "Production Orders",
    "fabrica.tracking": "Time Tracking",
    "fabrica.quality": "Quality",
    "fabrica.stops": "Downtime",
    "fabrica.resources": "Resources",
    "fabrica.machines": "Machines",
    "fabrica.operators": "Operators",
    "fabrica.fiscal": "Tax/Fiscal",
    "fabrica.tax_table": "Tax Table",
    "fabrica.output": "Output",
    "fabrica.finished": "Finished Goods",
    "fabrica.review": "Sheet Review",
    "fabrica.tools": "Tools",
    "fabrica.agent": "Huggs Agent",
    "fabrica.qa_agent": "QA Agent",

    "comercial.dashboard": "Dashboard",
    "comercial.launches": "Launch Calendar",
    "comercial.ibge": "IBGE Data",
    "comercial.mining": "Lead Mining",
    "comercial.reactivation": "Reactivation",
    "comercial.municipalities": "Municipalities",
    "comercial.whitespace": "Whitespace",

    "eventos.events": "Events",
    "eventos.dashboard": "Dashboard",

    "precos.dashboard": "Dashboard",
    "precos.matrix": "Comparative Matrix",
    "precos.manage": "Manage Tables",
    "precos.approval": "Approval",
    "precos.client_portal": "Client Portal",
    "precos.access_control": "Access Control",

    "dept.expenses": "Expenses",
    "dept.dashboard": "Dashboard",

    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of your CRM",
    "dashboard.ai_insights": "AI Insights",
    "dashboard.activities_30d": "Activities - Last 30 Days",
    "dashboard.activities_timeline": "Timeline of registered activities",
    "dashboard.activities_label": "Activities",

    "widget.total_prospects": "Total Prospects",
    "widget.prospects_registered": "Registered prospects",
    "widget.in_negotiation": "In Negotiation",
    "widget.prospects_negotiation": "Prospects in negotiation",
    "widget.activities_today": "Activities Today",
    "widget.activities_registered": "Registered activities",

    "quick.prospects": "Prospects Module",
    "quick.prospects_desc": "Complete prospect and pipeline management",
    "quick.trade": "Trade Marketing Module",
    "quick.trade_desc": "POS monitoring and performance",
    "quick.financeiro": "Finance Module",
    "quick.financeiro_desc": "Account management and cash flow",
    "quick.fabrica": "Factory Module",
    "quick.fabrica_desc": "Production, formulas and quality",

    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.delete": "Delete",
    "action.edit": "Edit",
    "action.search": "Search",
    "action.filter": "Filter",
    "action.export": "Export",
    "action.refresh": "Refresh",
    "action.close": "Close",
    "action.confirm": "Confirm",
    "action.back": "Back",
    "action.next": "Next",

    "logout.title": "Logged out",
    "logout.description": "See you soon!",
  },
  es: {
    "system.title": "Sistema Huggs",
    "loading": "Cargando...",
    "nav.dashboard": "Panel",
    "nav.notifications": "Notificaciones",
    "nav.audit": "Auditoría",
    "nav.install_app": "Instalar App",
    "nav.settings": "Configuración",
    "nav.logout": "Salir",
    "nav.connected": "Conectado",
    "nav.all_modules": "Todos los Módulos",
    "nav.n_modules": "módulos",
    "lang.label": "Idioma",
    "lang.pt-BR": "Português (BR)",
    "lang.en": "English",
    "lang.es": "Español",
    "lang.ar": "العربية",
    "offline.message": "Estás sin conexión. Algunas funciones pueden estar limitadas. Los datos se sincronizarán cuando vuelvas a estar en línea.",
    "offline.poor": "Conexión inestable detectada. La app intentará reconectar automáticamente.",

    "module.prospects": "Prospectos",
    "module.financeiro": "Financiero",
    "module.marketing": "Marketing",
    "module.trade": "Trade Marketing",
    "module.fabrica": "Fábrica",
    "module.comercial": "Comercial",
    "module.eventos": "Eventos",
    "module.departamentos": "Departamentos",
    "module.precos": "Tablas de Precios",

    "prospects.overview": "Vista General",
    "prospects.list": "Lista de Prospectos",
    "prospects.kanban": "Kanban",
    "prospects.activities": "Actividades",
    "prospects.tasks": "Tareas",
    "prospects.demands": "Central de Demandas",
    "prospects.title": "Prospectos",
    "prospects.registered": "prospectos registrados",
    "prospects.new": "Nuevo Prospecto",
    "prospects.ai": "IA",
    "prospects.search": "Buscar por nombre, email, teléfono...",
    "prospects.filter_status": "Filtrar por estado",
    "prospects.all_status": "Todos los Estados",
    "prospects.update_list": "Actualizar Lista",
    "prospects.none_found": "No se encontraron prospectos",
    "prospects.loading_list": "Cargando prospectos...",

    "status.novo": "Nuevo",
    "status.em_contato": "En Contacto",
    "status.proposta_enviada": "Propuesta",
    "status.negociacao": "Negociación",
    "status.ganho": "Ganado",
    "status.perdido": "Perdido",

    "label.email": "Email",
    "label.phone": "Teléfono",
    "label.seller": "Vendedor",

    "financeiro.overview": "Vista General",
    "financeiro.consolidated": "Dashboard Consolidado",
    "financeiro.dre": "P&L Analítico",
    "financeiro.departments": "Vista por Departamento",
    "financeiro.trade_budget": "Gestión de Presupuestos",
    "financeiro.payments_center": "Central de Pagos",
    "financeiro.dept_approvals": "Aprobaciones Depts",
    "financeiro.payables": "Cuentas por Pagar",
    "financeiro.receivables": "Cuentas por Cobrar",
    "financeiro.cashflow": "Flujo de Caja",
    "financeiro.bank_balances": "Saldos Bancarios",
    "financeiro.chart_accounts": "Plan de Cuentas",
    "financeiro.classify_bank": "Clasificar Banco",

    "trade.admin": "Administrativo",
    "trade.my_team": "Mi Equipo",
    "trade.pdvs": "PDVs",
    "trade.visits": "Visitas",
    "trade.sellout": "Sell Out",
    "trade.shelf": "Medición Estantes",
    "trade.brands": "Nuestras Marcas",
    "trade.photos": "Fotos",
    "trade.ideal_photos": "Fotos Ideales",
    "trade.audit": "Auditoría Góndola",
    "trade.competitive": "Análisis Competitivo",
    "trade.rewards": "Premiaciones",
    "trade.whatsapp": "WhatsApp",
    "trade.ai_insights": "Insights IA",

    "marketing.dashboards": "Dashboards & IA",
    "marketing.overview": "Vista General",

    "fabrica.dashboard": "Dashboard",
    "fabrica.entry": "Entrada",
    "fabrica.nfe": "Recepción NF-e",
    "fabrica.raw_materials": "Materias Primas",
    "fabrica.production": "Producción",
    "fabrica.formulas": "Fórmulas (BOM)",
    "fabrica.planning": "Planificación MRP",
    "fabrica.orders": "Órdenes de Producción",
    "fabrica.tracking": "Registros",
    "fabrica.quality": "Calidad",
    "fabrica.stops": "Paradas",
    "fabrica.resources": "Recursos",
    "fabrica.machines": "Máquinas",
    "fabrica.operators": "Operadores",
    "fabrica.fiscal": "Fiscal",
    "fabrica.tax_table": "Tabla de Impuestos",
    "fabrica.output": "Salida",
    "fabrica.finished": "Productos Terminados",
    "fabrica.review": "Revisión de Fichas",
    "fabrica.tools": "Herramientas",
    "fabrica.agent": "Agente Huggs",
    "fabrica.qa_agent": "Agente de QA",

    "comercial.dashboard": "Dashboard",
    "comercial.launches": "Calendario de Lanzamientos",
    "comercial.ibge": "Datos IBGE",
    "comercial.mining": "Minería de Leads",
    "comercial.reactivation": "Reactivación",
    "comercial.municipalities": "Municipios",
    "comercial.whitespace": "Whitespace",

    "eventos.events": "Eventos",
    "eventos.dashboard": "Dashboard",

    "precos.dashboard": "Dashboard",
    "precos.matrix": "Matriz Comparativa",
    "precos.manage": "Gestionar Tablas",
    "precos.approval": "Aprobación",
    "precos.client_portal": "Portal Cliente",
    "precos.access_control": "Control de Acceso",

    "dept.expenses": "Gastos",
    "dept.dashboard": "Dashboard",

    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Vista general de tu CRM",
    "dashboard.ai_insights": "Insights de IA",
    "dashboard.activities_30d": "Actividades - Últimos 30 Días",
    "dashboard.activities_timeline": "Línea de tiempo de actividades registradas",
    "dashboard.activities_label": "Actividades",

    "widget.total_prospects": "Total de Prospectos",
    "widget.prospects_registered": "Prospectos registrados",
    "widget.in_negotiation": "En Negociación",
    "widget.prospects_negotiation": "Prospectos en negociación",
    "widget.activities_today": "Actividades Hoy",
    "widget.activities_registered": "Actividades registradas",

    "quick.prospects": "Módulo de Prospectos",
    "quick.prospects_desc": "Gestión completa de prospectos y pipeline",
    "quick.trade": "Módulo de Trade Marketing",
    "quick.trade_desc": "Monitoreo de PDVs y rendimiento",
    "quick.financeiro": "Módulo Financiero",
    "quick.financeiro_desc": "Gestión de cuentas y flujo de caja",
    "quick.fabrica": "Módulo Fábrica",
    "quick.fabrica_desc": "Producción, fórmulas y calidad",

    "action.save": "Guardar",
    "action.cancel": "Cancelar",
    "action.delete": "Eliminar",
    "action.edit": "Editar",
    "action.search": "Buscar",
    "action.filter": "Filtrar",
    "action.export": "Exportar",
    "action.refresh": "Actualizar",
    "action.close": "Cerrar",
    "action.confirm": "Confirmar",
    "action.back": "Volver",
    "action.next": "Siguiente",

    "logout.title": "Sesión cerrada",
    "logout.description": "¡Hasta pronto!",
  },
  ar: {
    "system.title": "نظام هاغز",
    "loading": "جاري التحميل...",
    "nav.dashboard": "لوحة التحكم",
    "nav.notifications": "الإشعارات",
    "nav.audit": "التدقيق",
    "nav.install_app": "تثبيت التطبيق",
    "nav.settings": "الإعدادات",
    "nav.logout": "خروج",
    "nav.connected": "متصل",
    "nav.all_modules": "جميع الوحدات",
    "nav.n_modules": "وحدات",
    "lang.label": "اللغة",
    "lang.pt-BR": "Português (BR)",
    "lang.en": "English",
    "lang.es": "Español",
    "lang.ar": "العربية",
    "offline.message": "أنت غير متصل. قد تكون بعض الميزات محدودة. ستتم مزامنة البيانات عند العودة للاتصال.",
    "offline.poor": "تم اكتشاف اتصال غير مستقر. سيحاول التطبيق إعادة الاتصال تلقائياً.",

    "module.prospects": "العملاء المحتملون",
    "module.financeiro": "المالية",
    "module.marketing": "التسويق",
    "module.trade": "تسويق التجارة",
    "module.fabrica": "المصنع",
    "module.comercial": "التجاري",
    "module.eventos": "الفعاليات",
    "module.departamentos": "الأقسام",
    "module.precos": "جداول الأسعار",

    "prospects.overview": "نظرة عامة",
    "prospects.list": "قائمة العملاء المحتملين",
    "prospects.kanban": "كانبان",
    "prospects.activities": "الأنشطة",
    "prospects.tasks": "المهام",
    "prospects.demands": "مركز الطلبات",
    "prospects.title": "العملاء المحتملون",
    "prospects.registered": "عملاء محتملون مسجلون",
    "prospects.new": "عميل محتمل جديد",
    "prospects.ai": "ذكاء اصطناعي",
    "prospects.search": "البحث بالاسم، البريد، الهاتف...",
    "prospects.filter_status": "تصفية حسب الحالة",
    "prospects.all_status": "جميع الحالات",
    "prospects.update_list": "تحديث القائمة",
    "prospects.none_found": "لم يتم العثور على عملاء محتملين",
    "prospects.loading_list": "جاري تحميل العملاء المحتملين...",

    "status.novo": "جديد",
    "status.em_contato": "قيد التواصل",
    "status.proposta_enviada": "عرض مقدم",
    "status.negociacao": "تفاوض",
    "status.ganho": "مكسوب",
    "status.perdido": "خسارة",

    "label.email": "البريد الإلكتروني",
    "label.phone": "الهاتف",
    "label.seller": "البائع",

    "financeiro.overview": "نظرة عامة",
    "financeiro.consolidated": "لوحة تحكم موحدة",
    "financeiro.dre": "قائمة الدخل التحليلية",
    "financeiro.departments": "عرض الأقسام",
    "financeiro.trade_budget": "إدارة الميزانيات",
    "financeiro.payments_center": "مركز المدفوعات",
    "financeiro.dept_approvals": "موافقات الأقسام",
    "financeiro.payables": "حسابات دائنة",
    "financeiro.receivables": "حسابات مدينة",
    "financeiro.cashflow": "التدفق النقدي",
    "financeiro.bank_balances": "أرصدة بنكية",
    "financeiro.chart_accounts": "دليل الحسابات",
    "financeiro.classify_bank": "تصنيف بنكي",

    "trade.admin": "إداري",
    "trade.my_team": "فريقي",
    "trade.pdvs": "نقاط البيع",
    "trade.visits": "الزيارات",
    "trade.sellout": "المبيعات",
    "trade.shelf": "قياس الرفوف",
    "trade.brands": "علاماتنا التجارية",
    "trade.photos": "الصور",
    "trade.ideal_photos": "صور مثالية",
    "trade.audit": "تدقيق الرفوف",
    "trade.competitive": "تحليل تنافسي",
    "trade.rewards": "المكافآت",
    "trade.whatsapp": "واتساب",
    "trade.ai_insights": "رؤى الذكاء الاصطناعي",

    "marketing.dashboards": "لوحات التحكم والذكاء الاصطناعي",
    "marketing.overview": "نظرة عامة",

    "fabrica.dashboard": "لوحة التحكم",
    "fabrica.entry": "الاستلام",
    "fabrica.nfe": "استلام الفواتير",
    "fabrica.raw_materials": "المواد الخام",
    "fabrica.production": "الإنتاج",
    "fabrica.formulas": "التركيبات",
    "fabrica.planning": "تخطيط MRP",
    "fabrica.orders": "أوامر الإنتاج",
    "fabrica.tracking": "التسجيل",
    "fabrica.quality": "الجودة",
    "fabrica.stops": "التوقفات",
    "fabrica.resources": "الموارد",
    "fabrica.machines": "الآلات",
    "fabrica.operators": "المشغلون",
    "fabrica.fiscal": "الضريبي",
    "fabrica.tax_table": "جدول الضرائب",
    "fabrica.output": "المخرجات",
    "fabrica.finished": "منتجات جاهزة",
    "fabrica.review": "مراجعة البطاقات",
    "fabrica.tools": "أدوات",
    "fabrica.agent": "وكيل هاغز",
    "fabrica.qa_agent": "وكيل الجودة",

    "comercial.dashboard": "لوحة التحكم",
    "comercial.launches": "تقويم الإطلاقات",
    "comercial.ibge": "بيانات IBGE",
    "comercial.mining": "تعدين العملاء",
    "comercial.reactivation": "إعادة التنشيط",
    "comercial.municipalities": "البلديات",
    "comercial.whitespace": "المساحة البيضاء",

    "eventos.events": "الفعاليات",
    "eventos.dashboard": "لوحة التحكم",

    "precos.dashboard": "لوحة التحكم",
    "precos.matrix": "مصفوفة مقارنة",
    "precos.manage": "إدارة الجداول",
    "precos.approval": "الموافقة",
    "precos.client_portal": "بوابة العميل",
    "precos.access_control": "التحكم بالوصول",

    "dept.expenses": "المصروفات",
    "dept.dashboard": "لوحة التحكم",

    "dashboard.title": "لوحة التحكم",
    "dashboard.subtitle": "نظرة عامة على نظام إدارة العلاقات",
    "dashboard.ai_insights": "رؤى الذكاء الاصطناعي",
    "dashboard.activities_30d": "الأنشطة - آخر 30 يوم",
    "dashboard.activities_timeline": "الجدول الزمني للأنشطة المسجلة",
    "dashboard.activities_label": "الأنشطة",

    "widget.total_prospects": "إجمالي العملاء المحتملين",
    "widget.prospects_registered": "عملاء محتملون مسجلون",
    "widget.in_negotiation": "قيد التفاوض",
    "widget.prospects_negotiation": "عملاء محتملون في مرحلة التفاوض",
    "widget.activities_today": "أنشطة اليوم",
    "widget.activities_registered": "أنشطة مسجلة",

    "quick.prospects": "وحدة العملاء المحتملين",
    "quick.prospects_desc": "إدارة كاملة للعملاء المحتملين",
    "quick.trade": "وحدة تسويق التجارة",
    "quick.trade_desc": "مراقبة نقاط البيع والأداء",
    "quick.financeiro": "الوحدة المالية",
    "quick.financeiro_desc": "إدارة الحسابات والتدفق النقدي",
    "quick.fabrica": "وحدة المصنع",
    "quick.fabrica_desc": "الإنتاج والتركيبات والجودة",

    "action.save": "حفظ",
    "action.cancel": "إلغاء",
    "action.delete": "حذف",
    "action.edit": "تعديل",
    "action.search": "بحث",
    "action.filter": "تصفية",
    "action.export": "تصدير",
    "action.refresh": "تحديث",
    "action.close": "إغلاق",
    "action.confirm": "تأكيد",
    "action.back": "رجوع",
    "action.next": "التالي",

    "logout.title": "تم تسجيل الخروج",
    "logout.description": "إلى اللقاء!",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "pt-BR";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["pt-BR"]?.[key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
