import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "pt-BR" | "en" | "es" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  "pt-BR": {
    // Sistema
    "system.title": "Sistema Huggs",
    "loading": "Carregando...",

    // Navegação geral
    "nav.dashboard": "Dashboard",
    "nav.notifications": "Notificações",
    "nav.audit": "Auditoria",
    "nav.install_app": "Instalar App",
    "nav.settings": "Configurações",
    "nav.logout": "Sair",
    "nav.connected": "Conectado",
    "nav.all_modules": "Todos os Módulos",
    "nav.n_modules": "módulos",

    // Idioma
    "lang.label": "Idioma",
    "lang.pt-BR": "Português (BR)",
    "lang.en": "English",
    "lang.es": "Español",
    "lang.ar": "العربية",

    // Offline
    "offline.message": "Você está offline. Algumas funcionalidades podem estar limitadas. Os dados serão sincronizados quando você voltar online.",
    "offline.poor": "Conexão instável detectada. O aplicativo tentará reconectar automaticamente se houver falhas.",

    // Módulos (sidebar headers)
    "module.prospects": "Prospects",
    "module.financeiro": "Financeiro",
    "module.marketing": "Marketing",
    "module.trade": "Trade Marketing",
    "module.fabrica": "Fábrica",
    "module.comercial": "Comercial",
    "module.eventos": "Eventos",
    "module.departamentos": "Departamentos",
    "module.precos": "Tabelas de Preços",

    // Prospects submenus
    "prospects.overview": "Visão Geral",
    "prospects.list": "Lista de Prospects",
    "prospects.kanban": "Kanban",
    "prospects.activities": "Atividades",
    "prospects.tasks": "Tarefas",
    "prospects.demands": "Central de Demandas",
    "prospects.title": "Prospects",
    "prospects.registered": "prospects cadastrados",
    "prospects.new": "Novo Prospect",
    "prospects.ai": "IA",
    "prospects.search": "Buscar por nome, email, telefone...",
    "prospects.filter_status": "Filtrar por status",
    "prospects.all_status": "Todos os Status",
    "prospects.update_list": "Atualizar Lista",
    "prospects.none_found": "Nenhum prospect encontrado",
    "prospects.loading_list": "Carregando prospects...",

    // Status
    "status.novo": "Novo",
    "status.em_contato": "Em Contato",
    "status.proposta_enviada": "Proposta",
    "status.negociacao": "Negociação",
    "status.ganho": "Ganho",
    "status.perdido": "Perdido",

    // Labels comuns
    "label.email": "Email",
    "label.phone": "Telefone",
    "label.seller": "Vendedor",

    // Financeiro submenus
    "financeiro.overview": "Visão Geral",
    "financeiro.consolidated": "Dashboard Consolidado",
    "financeiro.dre": "DRE Analítico",
    "financeiro.departments": "Visão por Departamento",
    "financeiro.trade_budget": "Gestão de Verbas",
    "financeiro.payments_center": "Central de Pagamentos",
    "financeiro.dept_approvals": "Aprovações Depts",
    "financeiro.payables": "Contas a Pagar",
    "financeiro.receivables": "Contas a Receber",
    "financeiro.cashflow": "Fluxo de Caixa",
    "financeiro.bank_balances": "Saldos Bancários",
    "financeiro.chart_accounts": "Plano de Contas",
    "financeiro.classify_bank": "Classificar Banco",

    // Trade submenus
    "trade.admin": "Administrativo",
    "trade.my_team": "Minha Equipe",
    "trade.pdvs": "PDVs",
    "trade.visits": "Visitas",
    "trade.sellout": "Sell Out",
    "trade.shelf": "Medição Prateleiras",
    "trade.brands": "Nossas Marcas",
    "trade.photos": "Fotos",
    "trade.ideal_photos": "Fotos Ideais",
    "trade.audit": "Auditoria Gôndola",
    "trade.competitive": "Análise Competitiva",
    "trade.rewards": "Premiações",
    "trade.whatsapp": "WhatsApp",
    "trade.ai_insights": "Insights IA",

    // Marketing submenus
    "marketing.dashboards": "Dashboards & IA",
    "marketing.overview": "Visão Geral",

    // Fábrica groups
    "fabrica.dashboard": "Dashboard",
    "fabrica.entry": "Entrada",
    "fabrica.nfe": "Recebimento NF-e",
    "fabrica.raw_materials": "Matérias-Primas",
    "fabrica.production": "Produção",
    "fabrica.formulas": "Fórmulas (BOM)",
    "fabrica.planning": "Planejamento MRP",
    "fabrica.orders": "Ordens de Produção",
    "fabrica.tracking": "Apontamentos",
    "fabrica.quality": "Qualidade",
    "fabrica.stops": "Paradas",
    "fabrica.resources": "Recursos",
    "fabrica.machines": "Máquinas",
    "fabrica.operators": "Operadores",
    "fabrica.fiscal": "Fiscal",
    "fabrica.tax_table": "Tabela de Impostos",
    "fabrica.output": "Saída",
    "fabrica.finished": "Produtos Acabados",
    "fabrica.review": "Revisão de Fichas",
    "fabrica.tools": "Ferramentas",
    "fabrica.agent": "Agente Huggs",
    "fabrica.qa_agent": "Agente de QA",

    // Comercial submenus
    "comercial.dashboard": "Dashboard",
    "comercial.launches": "Calendário de Lançamentos",
    "comercial.ibge": "Dados IBGE",
    "comercial.mining": "Mineração de Leads",
    "comercial.reactivation": "Reativação",
    "comercial.municipalities": "Municípios",
    "comercial.whitespace": "Whitespace",

    // Eventos submenus
    "eventos.events": "Eventos",
    "eventos.dashboard": "Dashboard",

    // Preços submenus
    "precos.dashboard": "Dashboard",
    "precos.matrix": "Matriz Comparativa",
    "precos.manage": "Gerenciar Tabelas",
    "precos.approval": "Aprovação",
    "precos.client_portal": "Portal Cliente",
    "precos.access_control": "Controle de Acesso",

    // Departamentos submenus
    "dept.expenses": "Despesas",
    "dept.dashboard": "Dashboard",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Visão geral do seu CRM",
    "dashboard.ai_insights": "Insights de IA",
    "dashboard.activities_30d": "Atividades - Últimos 30 Dias",
    "dashboard.activities_timeline": "Linha do tempo de atividades registradas",
    "dashboard.activities_label": "Atividades",

    // Dashboard widgets
    "widget.total_prospects": "Total de Prospects",
    "widget.prospects_registered": "Prospects cadastrados",
    "widget.in_negotiation": "Em Negociação",
    "widget.prospects_negotiation": "Prospects em negociação",
    "widget.activities_today": "Atividades Hoje",
    "widget.activities_registered": "Atividades registradas",

    // Módulos rápidos
    "quick.prospects": "Módulo de Prospects",
    "quick.prospects_desc": "Gestão completa de prospects e pipeline",
    "quick.trade": "Módulo de Trade Marketing",
    "quick.trade_desc": "Monitoramento de PDVs e performance",
    "quick.financeiro": "Módulo Financeiro",
    "quick.financeiro_desc": "Gestão de contas e fluxo de caixa",
    "quick.fabrica": "Módulo Fábrica",
    "quick.fabrica_desc": "Produção, fórmulas e qualidade",

    // Ações comuns
    "action.save": "Salvar",
    "action.cancel": "Cancelar",
    "action.delete": "Excluir",
    "action.edit": "Editar",
    "action.search": "Buscar",
    "action.filter": "Filtrar",
    "action.export": "Exportar",
    "action.refresh": "Atualizar",
    "action.close": "Fechar",
    "action.confirm": "Confirmar",
    "action.back": "Voltar",
    "action.next": "Próximo",

    // Trade Widget
    "trade_w.active_stores": "PDVs Ativos",
    "trade_w.active_stores_desc": "Pontos de venda",
    "trade_w.monthly_visits": "Visitas do Mês",
    "trade_w.monthly_visits_desc": "Visitas realizadas",
    "trade_w.monthly_photos": "Fotos do Mês",
    "trade_w.monthly_photos_desc": "Fotos enviadas",
    "trade_w.investments": "Investimentos",
    "trade_w.investments_desc": "Total do mês",

    // Finance Widget
    "fin_w.payable_pending": "A Pagar (Pendentes)",
    "fin_w.payable_overdue": "A Pagar (Vencidas)",
    "fin_w.total_payable": "Total a Pagar",
    "fin_w.payable_overdue_val": "Pagar Vencido",
    "fin_w.receivable_pending": "A Receber (Pendentes)",
    "fin_w.receivable_overdue": "A Receber (Vencidas)",
    "fin_w.total_receivable": "Total a Receber",
    "fin_w.receivable_overdue_val": "Receber Vencido",
    "fin_w.section_payable": "Contas a Pagar",
    "fin_w.section_receivable": "Contas a Receber",
    "fin_w.titles_due": "Títulos a vencer",
    "fin_w.attention_needed": "Atenção necessária",
    "fin_w.pending_value": "Valor pendente",
    "fin_w.overdue_value": "Valor em atraso",
    "fin_w.delinquency": "Inadimplência",

    // Executive KPIs
    "exec.total_prospects": "Total de Prospects",
    "exec.visits_30d": "Visitas (30 dias)",
    "exec.conversion_rate": "Taxa de Conversão",
    "exec.avg_ticket": "Ticket Médio",
    "exec.active_goals": "Metas Ativas",
    "exec.vs_previous": "vs período anterior",

    // Funnel
    "funnel.title": "Funil de Prospecção",
    "funnel.description": "Taxa de conversão por etapa do processo",
    "funnel.prospects_label": "Prospects",
    "funnel.percentage_label": "Percentual",

    // Brand Share
    "brand.total_measurements": "Total Medições",
    "brand.measurements_period": "medições no período",
    "brand.avg_share": "Share Médio",
    "brand.avg_share_desc": "das nossas marcas",
    "brand.leading_brand": "Marca Líder",
    "brand.leading_brand_desc": "maior espaço ocupado",
    "brand.growth": "Crescimento",
    "brand.growth_desc": "vs. período anterior",
    "brand.distribution": "Distribuição por Marca",
    "brand.monthly_evolution": "Evolução Mensal por Marca",
    "brand.store_ranking": "Ranking de Lojas por Share",
    "brand.measurements": "medições",
    "brand.no_data": "Sem dados para exibir",

    // Trade Executive
    "trade_exec.active_stores": "PDVs Ativos",
    "trade_exec.monthly_visits": "Visitas do Mês",
    "trade_exec.monthly_photos": "Fotos do Mês",
    "trade_exec.avg_roi": "ROI Médio",
    "trade_exec.top_clients": "Top 10 Clientes por Lançamentos",
    "trade_exec.total_value": "Valor Total",
    "trade_exec.no_entries": "Nenhum lançamento encontrado",
    "trade_exec.recent_photos": "Fotos Recentes",
    "trade_exec.pending": "Pendente",
    "trade_exec.no_photos": "Nenhuma foto encontrada",

    // Approval KPIs
    "approval.total_pending": "Total Pendente",
    "approval.campaigns": "Campanhas",
    "approval.entries": "Lançamentos",
    "approval.total_value": "Valor Total",
    "approval.status": "Status",
    "approval.review": "Revisar",
    "approval.up_to_date": "Em dia ✓",

    // Comercial
    "comercial.untapped": "Potencial Não Explorado",
    "comercial.no_purchase": "clientes cadastrados sem nenhuma compra registrada",

    // Logout
    "logout.title": "Logout realizado",
    "logout.description": "Até logo!",

    // Finance Dashboard - Contas a Pagar
    "fin.avg_payment_term": "Prazo Médio Pagamento",
    "fin.avg_payment_desc": "Média entre emissão e pagamento",
    "fin.punctuality_index": "Índice de Pontualidade",
    "fin.paid_on_time": "Pagos no prazo ou antes",
    "fin.current_month": "Mês Atual",
    "fin.vs_prev_month": "vs mês anterior",
    "fin.no_variation": "Sem variação",
    "fin.next_30_days": "Próximos 30 dias",
    "fin.due_in_period": "A vencer no período",
    "fin.due_today": "Vencendo Hoje",
    "fin.titles": "títulos",
    "fin.next_7_days": "Próximos 7 Dias",
    "fin.overdue_30d": "Vencidas +30 dias",
    "fin.monthly_evolution": "Evolução Mensal",
    "fin.payments_vs_pending": "Pagamentos realizados vs pendentes",
    "fin.area": "Área",
    "fin.bars": "Barras",
    "fin.lines": "Linhas",
    "fin.paid": "Pago",
    "fin.pending": "Pendente",
    "fin.by_department": "Por Departamento",
    "fin.expense_distribution": "Distribuição de despesas",
    "fin.by_status": "Por Status",
    "fin.title_status": "Situação dos títulos",
    "fin.top10_suppliers": "Top 10 Fornecedores",
    "fin.by_total_value": "Por valor total",
    "fin.loading_data": "Carregando dados consolidados...",
    "fin.days": "dias",

    // Finance Dashboard - Contas a Receber
    "fin.avg_receipt_term": "Prazo Médio Recebimento",
    "fin.avg_receipt_desc": "Média entre emissão e recebimento",
    "fin.received_on_time": "Recebidos no prazo ou antes",
    "fin.to_receive_period": "A receber no período",
    "fin.received": "Recebido",
    "fin.receipts_vs_pending": "Recebimentos realizados vs pendentes",
    "fin.top10_clients_open": "Top 10 Clientes (em aberto)",
    "fin.highest_receivable": "Maiores valores a receber",
    "fin.receivable_by_term": "A Receber por Prazo",
    "fin.distribution_by_term": "Distribuição por faixa de vencimento",
    "fin.status_distribution": "Distribuição por Status",
    "fin.value_by_status": "Proporção de valores por situação",

    // Finance - Fluxo de Caixa / Verbas
    "fin.cashflow_events": "Fluxo de Caixa Eventos",
    "fin.cashflow_dept": "Fluxo de Caixa",
    "fin.last_6_months": "Últimos 6 meses",
    "fin.inflows": "Entradas",
    "fin.outflows": "Saídas",
    "fin.balance": "Saldo",
    "fin.accumulated_balance": "Saldo Acumulado",
    "fin.event_budgets": "Verbas de Eventos",
    "fin.dept_budgets": "Verbas do Departamento",
    "fin.view_all_budgets": "Ver todas as verbas",
    "fin.total_budgeted": "Total Orçado",
    "fin.used": "Utilizado",
    "fin.available": "Disponível",
    "fin.utilization": "Utilização",
    "fin.no_budgets_found": "Nenhuma verba encontrada",
    "fin.no_event_budgets": "Nenhuma verba de eventos encontrada",

    // Trade Finance Page
    "trade_fin.title": "Financeiro Trade Marketing",
    "trade_fin.subtitle": "Gestão de verbas, investimentos e plano de contas",
    "trade_fin.full_module": "Módulo Financeiro Completo",
    "trade_fin.dashboard": "Dashboard Financeiro",
    "trade_fin.dashboard_desc": "Visão consolidada de verbas e campanhas",
    "trade_fin.my_statement": "Meu Extrato",
    "trade_fin.statement_desc": "Histórico de lançamentos e aprovações",
    "trade_fin.campaigns": "Campanhas",
    "trade_fin.campaigns_desc": "Gestão administrativa de campanhas",
    "trade_fin.entries_panel": "Painel de Lançamentos",
    "trade_fin.entries_desc": "Resultados e execução de campanhas",
    "trade_fin.current_accounts": "Contas Correntes",
    "trade_fin.current_desc": "Gestão de contas correntes por cliente",
    "trade_fin.semester_budgets": "Verbas Semestrais",
    "trade_fin.semester_desc": "Planejamento e acompanhamento semestral",
    "trade_fin.entries": "Lançamentos",
    "trade_fin.entries_all_desc": "Todos os lançamentos financeiros",
    "trade_fin.approvals": "Aprovações",
    "trade_fin.approvals_desc": "Revisar e aprovar lançamentos pendentes",
    "trade_fin.payables": "Contas a Pagar",
    "trade_fin.payables_desc": "Gestão de contas e orçamentos",
    "trade_fin.search_client": "Buscar Cliente",
    "trade_fin.search_placeholder": "Digite o nome, código, CNPJ, cidade ou endereço...",
    "trade_fin.smart_filter": "Filtro Inteligente (IA)",
    "trade_fin.clear": "Limpar",
    "trade_fin.no_client_found": "Nenhum cliente encontrado",

    // Marketing Page
    "mkt.title": "Marketing",
    "mkt.subtitle": "Relatórios e dashboards integrados",
    "mkt.back_menu": "Voltar ao Menu",
    "mkt.mission_control": "Mission Control",
    "mkt.mission_desc": "Central de tarefas de marketing para lançamentos",
    "mkt.instagram_desc": "Análises e métricas do Instagram",
    "mkt.dashcortex_desc": "Relatórios integrados DashCortex",
    "mkt.powerbi_desc": "Dashboards e visualizações Power BI",
    "mkt.social": "Redes Sociais",
    "mkt.social_desc": "Gerenciar contas e métricas sociais",
    "mkt.elevenlabs_desc": "Áudio, voz e música com IA",
    "mkt.access": "Acessar",
    "mkt.new": "NOVO",

    // Marketing Charts
    "mkt.followers_evolution": "Evolução de Seguidores",
    "mkt.followers": "Seguidores",
    "mkt.engagement_reach": "Engajamento & Alcance",
    "mkt.engagement_pct": "Engajamento %",
    "mkt.reach": "Alcance",
    "mkt.publications": "Publicações",

    // Editorial Calendar
    "mkt.editorial_calendar": "Calendário Editorial",
    "mkt.today": "Hoje",
    "mkt.more": "mais",
    "mkt.posts_of": "Posts de",
    "mkt.no_posts_day": "Nenhum post agendado para este dia",
    "mkt.media_count": "mídia(s)",
    "mkt.accounts_selected": "conta(s) selecionada(s)",
    "mkt.status_scheduled": "Agendado",
    "mkt.status_published": "Publicado",
    "mkt.status_failed": "Falhou",
    "mkt.status_publishing": "Publicando",
    "mkt.status_draft": "Rascunho",
    "mkt.weekdays": "Dom,Seg,Ter,Qua,Qui,Sex,Sáb",

    // Trade Expense Categories
    "trade_cat.material_pos": "Material POS",
    "trade_cat.degustacao": "Degustação",
    "trade_cat.promocao": "Promoção",
    "trade_cat.bonificacao": "Bonificação",
    "trade_cat.logistica": "Logística",
    "trade_cat.merchandising": "Merchandising",
    "trade_cat.enxoval": "Enxoval",
    "trade_cat.midia": "Mídia / Comunicação",
    "trade_cat.evento": "Evento",
    "trade_cat.treinamento": "Treinamento",
    "trade_cat.outros": "Outros",
  },
  en: {
    "system.title": "Huggs System",
    "loading": "Loading...",
    "nav.dashboard": "Dashboard",
    "nav.notifications": "Notifications",
    "nav.audit": "Audit",
    "nav.install_app": "Install App",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    "nav.connected": "Connected",
    "nav.all_modules": "All Modules",
    "nav.n_modules": "modules",
    "lang.label": "Language",
    "lang.pt-BR": "Português (BR)",
    "lang.en": "English",
    "lang.es": "Español",
    "lang.ar": "العربية",
    "offline.message": "You are offline. Some features may be limited. Data will sync when you're back online.",
    "offline.poor": "Unstable connection detected. The app will try to reconnect automatically.",

    "module.prospects": "Prospects",
    "module.financeiro": "Finance",
    "module.marketing": "Marketing",
    "module.trade": "Trade Marketing",
    "module.fabrica": "Factory",
    "module.comercial": "Commercial",
    "module.eventos": "Events",
    "module.departamentos": "Departments",
    "module.precos": "Price Tables",

    "prospects.overview": "Overview",
    "prospects.list": "Prospect List",
    "prospects.kanban": "Kanban",
    "prospects.activities": "Activities",
    "prospects.tasks": "Tasks",
    "prospects.demands": "Demand Center",
    "prospects.title": "Prospects",
    "prospects.registered": "registered prospects",
    "prospects.new": "New Prospect",
    "prospects.ai": "AI",
    "prospects.search": "Search by name, email, phone...",
    "prospects.filter_status": "Filter by status",
    "prospects.all_status": "All Statuses",
    "prospects.update_list": "Refresh List",
    "prospects.none_found": "No prospects found",
    "prospects.loading_list": "Loading prospects...",

    "status.novo": "New",
    "status.em_contato": "In Contact",
    "status.proposta_enviada": "Proposal",
    "status.negociacao": "Negotiation",
    "status.ganho": "Won",
    "status.perdido": "Lost",

    "label.email": "Email",
    "label.phone": "Phone",
    "label.seller": "Seller",

    "financeiro.overview": "Overview",
    "financeiro.consolidated": "Consolidated Dashboard",
    "financeiro.dre": "Analytical P&L",
    "financeiro.departments": "Department View",
    "financeiro.trade_budget": "Budget Management",
    "financeiro.payments_center": "Payment Center",
    "financeiro.dept_approvals": "Dept. Approvals",
    "financeiro.payables": "Accounts Payable",
    "financeiro.receivables": "Accounts Receivable",
    "financeiro.cashflow": "Cash Flow",
    "financeiro.bank_balances": "Bank Balances",
    "financeiro.chart_accounts": "Chart of Accounts",
    "financeiro.classify_bank": "Bank Classification",

    "trade.admin": "Administrative",
    "trade.my_team": "My Team",
    "trade.pdvs": "Stores",
    "trade.visits": "Visits",
    "trade.sellout": "Sell Out",
    "trade.shelf": "Shelf Measurement",
    "trade.brands": "Our Brands",
    "trade.photos": "Photos",
    "trade.ideal_photos": "Ideal Photos",
    "trade.audit": "Shelf Audit",
    "trade.competitive": "Competitive Analysis",
    "trade.rewards": "Rewards",
    "trade.whatsapp": "WhatsApp",
    "trade.ai_insights": "AI Insights",

    "marketing.dashboards": "Dashboards & AI",
    "marketing.overview": "Overview",

    "fabrica.dashboard": "Dashboard",
    "fabrica.entry": "Receiving",
    "fabrica.nfe": "NF-e Receipt",
    "fabrica.raw_materials": "Raw Materials",
    "fabrica.production": "Production",
    "fabrica.formulas": "Formulas (BOM)",
    "fabrica.planning": "MRP Planning",
    "fabrica.orders": "Production Orders",
    "fabrica.tracking": "Time Tracking",
    "fabrica.quality": "Quality",
    "fabrica.stops": "Downtime",
    "fabrica.resources": "Resources",
    "fabrica.machines": "Machines",
    "fabrica.operators": "Operators",
    "fabrica.fiscal": "Tax/Fiscal",
    "fabrica.tax_table": "Tax Table",
    "fabrica.output": "Output",
    "fabrica.finished": "Finished Goods",
    "fabrica.review": "Sheet Review",
    "fabrica.tools": "Tools",
    "fabrica.agent": "Huggs Agent",
    "fabrica.qa_agent": "QA Agent",

    "comercial.dashboard": "Dashboard",
    "comercial.launches": "Launch Calendar",
    "comercial.ibge": "IBGE Data",
    "comercial.mining": "Lead Mining",
    "comercial.reactivation": "Reactivation",
    "comercial.municipalities": "Municipalities",
    "comercial.whitespace": "Whitespace",

    "eventos.events": "Events",
    "eventos.dashboard": "Dashboard",

    "precos.dashboard": "Dashboard",
    "precos.matrix": "Comparative Matrix",
    "precos.manage": "Manage Tables",
    "precos.approval": "Approval",
    "precos.client_portal": "Client Portal",
    "precos.access_control": "Access Control",

    "dept.expenses": "Expenses",
    "dept.dashboard": "Dashboard",

    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of your CRM",
    "dashboard.ai_insights": "AI Insights",
    "dashboard.activities_30d": "Activities - Last 30 Days",
    "dashboard.activities_timeline": "Timeline of registered activities",
    "dashboard.activities_label": "Activities",

    "widget.total_prospects": "Total Prospects",
    "widget.prospects_registered": "Registered prospects",
    "widget.in_negotiation": "In Negotiation",
    "widget.prospects_negotiation": "Prospects in negotiation",
    "widget.activities_today": "Activities Today",
    "widget.activities_registered": "Registered activities",

    "quick.prospects": "Prospects Module",
    "quick.prospects_desc": "Complete prospect and pipeline management",
    "quick.trade": "Trade Marketing Module",
    "quick.trade_desc": "POS monitoring and performance",
    "quick.financeiro": "Finance Module",
    "quick.financeiro_desc": "Account management and cash flow",
    "quick.fabrica": "Factory Module",
    "quick.fabrica_desc": "Production, formulas and quality",

    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.delete": "Delete",
    "action.edit": "Edit",
    "action.search": "Search",
    "action.filter": "Filter",
    "action.export": "Export",
    "action.refresh": "Refresh",
    "action.close": "Close",
    "action.confirm": "Confirm",
    "action.back": "Back",
    "action.next": "Next",

    "trade_w.active_stores": "Active Stores",
    "trade_w.active_stores_desc": "Points of sale",
    "trade_w.monthly_visits": "Monthly Visits",
    "trade_w.monthly_visits_desc": "Visits completed",
    "trade_w.monthly_photos": "Monthly Photos",
    "trade_w.monthly_photos_desc": "Photos sent",
    "trade_w.investments": "Investments",
    "trade_w.investments_desc": "Monthly total",

    "fin_w.payable_pending": "Payable (Pending)",
    "fin_w.payable_overdue": "Payable (Overdue)",
    "fin_w.total_payable": "Total Payable",
    "fin_w.payable_overdue_val": "Payable Overdue",
    "fin_w.receivable_pending": "Receivable (Pending)",
    "fin_w.receivable_overdue": "Receivable (Overdue)",
    "fin_w.total_receivable": "Total Receivable",
    "fin_w.receivable_overdue_val": "Receivable Overdue",
    "fin_w.section_payable": "Accounts Payable",
    "fin_w.section_receivable": "Accounts Receivable",
    "fin_w.titles_due": "Titles due",
    "fin_w.attention_needed": "Attention needed",
    "fin_w.pending_value": "Pending value",
    "fin_w.overdue_value": "Overdue value",
    "fin_w.delinquency": "Delinquency",

    "exec.total_prospects": "Total Prospects",
    "exec.visits_30d": "Visits (30 days)",
    "exec.conversion_rate": "Conversion Rate",
    "exec.avg_ticket": "Avg Ticket",
    "exec.active_goals": "Active Goals",
    "exec.vs_previous": "vs previous period",

    "funnel.title": "Prospecting Funnel",
    "funnel.description": "Conversion rate by stage",
    "funnel.prospects_label": "Prospects",
    "funnel.percentage_label": "Percentage",

    "brand.total_measurements": "Total Measurements",
    "brand.measurements_period": "measurements in period",
    "brand.avg_share": "Avg Share",
    "brand.avg_share_desc": "of our brands",
    "brand.leading_brand": "Leading Brand",
    "brand.leading_brand_desc": "most shelf space",
    "brand.growth": "Growth",
    "brand.growth_desc": "vs. previous period",
    "brand.distribution": "Brand Distribution",
    "brand.monthly_evolution": "Monthly Brand Evolution",
    "brand.store_ranking": "Store Share Ranking",
    "brand.measurements": "measurements",
    "brand.no_data": "No data to display",

    "trade_exec.active_stores": "Active Stores",
    "trade_exec.monthly_visits": "Monthly Visits",
    "trade_exec.monthly_photos": "Monthly Photos",
    "trade_exec.avg_roi": "Avg ROI",
    "trade_exec.top_clients": "Top 10 Clients by Entries",
    "trade_exec.total_value": "Total Value",
    "trade_exec.no_entries": "No entries found",
    "trade_exec.recent_photos": "Recent Photos",
    "trade_exec.pending": "Pending",
    "trade_exec.no_photos": "No photos found",

    "approval.total_pending": "Total Pending",
    "approval.campaigns": "Campaigns",
    "approval.entries": "Entries",
    "approval.total_value": "Total Value",
    "approval.status": "Status",
    "approval.review": "Review",
    "approval.up_to_date": "Up to date ✓",

    "comercial.untapped": "Untapped Potential",
    "comercial.no_purchase": "registered clients with no purchases",

    "logout.title": "Logged out",
    "logout.description": "See you soon!",

    "fin.avg_payment_term": "Avg Payment Term",
    "fin.avg_payment_desc": "Average between issue and payment",
    "fin.punctuality_index": "Punctuality Index",
    "fin.paid_on_time": "Paid on time or early",
    "fin.current_month": "Current Month",
    "fin.vs_prev_month": "vs previous month",
    "fin.no_variation": "No variation",
    "fin.next_30_days": "Next 30 days",
    "fin.due_in_period": "Due in period",
    "fin.due_today": "Due Today",
    "fin.titles": "titles",
    "fin.next_7_days": "Next 7 Days",
    "fin.overdue_30d": "Overdue +30 days",
    "fin.monthly_evolution": "Monthly Evolution",
    "fin.payments_vs_pending": "Payments made vs pending",
    "fin.area": "Area",
    "fin.bars": "Bars",
    "fin.lines": "Lines",
    "fin.paid": "Paid",
    "fin.pending": "Pending",
    "fin.by_department": "By Department",
    "fin.expense_distribution": "Expense distribution",
    "fin.by_status": "By Status",
    "fin.title_status": "Title status",
    "fin.top10_suppliers": "Top 10 Suppliers",
    "fin.by_total_value": "By total value",
    "fin.loading_data": "Loading consolidated data...",
    "fin.days": "days",
    "fin.avg_receipt_term": "Avg Receipt Term",
    "fin.avg_receipt_desc": "Average between issue and receipt",
    "fin.received_on_time": "Received on time or early",
    "fin.to_receive_period": "To receive in period",
    "fin.received": "Received",
    "fin.receipts_vs_pending": "Receipts made vs pending",
    "fin.top10_clients_open": "Top 10 Clients (open)",
    "fin.highest_receivable": "Highest receivable values",
    "fin.receivable_by_term": "Receivable by Term",
    "fin.distribution_by_term": "Distribution by due date range",
    "fin.status_distribution": "Status Distribution",
    "fin.value_by_status": "Value proportion by status",
    "fin.cashflow_events": "Events Cash Flow",
    "fin.cashflow_dept": "Cash Flow",
    "fin.last_6_months": "Last 6 months",
    "fin.inflows": "Inflows",
    "fin.outflows": "Outflows",
    "fin.balance": "Balance",
    "fin.accumulated_balance": "Accumulated Balance",
    "fin.event_budgets": "Event Budgets",
    "fin.dept_budgets": "Department Budgets",
    "fin.view_all_budgets": "View all budgets",
    "fin.total_budgeted": "Total Budgeted",
    "fin.used": "Used",
    "fin.available": "Available",
    "fin.utilization": "Utilization",
    "fin.no_budgets_found": "No budgets found",
    "fin.no_event_budgets": "No event budgets found",
    "trade_fin.title": "Trade Marketing Finance",
    "trade_fin.subtitle": "Budget, investment and chart of accounts management",
    "trade_fin.full_module": "Full Finance Module",
    "trade_fin.dashboard": "Financial Dashboard",
    "trade_fin.dashboard_desc": "Consolidated view of budgets and campaigns",
    "trade_fin.my_statement": "My Statement",
    "trade_fin.statement_desc": "Entry and approval history",
    "trade_fin.campaigns": "Campaigns",
    "trade_fin.campaigns_desc": "Campaign administration",
    "trade_fin.entries_panel": "Entries Panel",
    "trade_fin.entries_desc": "Campaign results and execution",
    "trade_fin.current_accounts": "Current Accounts",
    "trade_fin.current_desc": "Current accounts by client",
    "trade_fin.semester_budgets": "Semester Budgets",
    "trade_fin.semester_desc": "Semester planning and tracking",
    "trade_fin.entries": "Entries",
    "trade_fin.entries_all_desc": "All financial entries",
    "trade_fin.approvals": "Approvals",
    "trade_fin.approvals_desc": "Review and approve pending entries",
    "trade_fin.payables": "Accounts Payable",
    "trade_fin.payables_desc": "Account and budget management",
    "trade_fin.search_client": "Search Client",
    "trade_fin.search_placeholder": "Type name, code, CNPJ, city or address...",
    "trade_fin.smart_filter": "Smart Filter (AI)",
    "trade_fin.clear": "Clear",
    "trade_fin.no_client_found": "No client found",
    "mkt.title": "Marketing",
    "mkt.subtitle": "Integrated reports and dashboards",
    "mkt.back_menu": "Back to Menu",
    "mkt.mission_control": "Mission Control",
    "mkt.mission_desc": "Marketing task center for launches",
    "mkt.instagram_desc": "Instagram analytics and metrics",
    "mkt.dashcortex_desc": "DashCortex integrated reports",
    "mkt.powerbi_desc": "Power BI dashboards and visualizations",
    "mkt.social": "Social Media",
    "mkt.social_desc": "Manage social accounts and metrics",
    "mkt.elevenlabs_desc": "AI audio, voice and music",
    "mkt.access": "Access",
    "mkt.new": "NEW",
    "mkt.followers_evolution": "Followers Evolution",
    "mkt.followers": "Followers",
    "mkt.engagement_reach": "Engagement & Reach",
    "mkt.engagement_pct": "Engagement %",
    "mkt.reach": "Reach",
    "mkt.publications": "Publications",
    "mkt.editorial_calendar": "Editorial Calendar",
    "mkt.today": "Today",
    "mkt.more": "more",
    "mkt.posts_of": "Posts from",
    "mkt.no_posts_day": "No posts scheduled for this day",
    "mkt.media_count": "media",
    "mkt.accounts_selected": "account(s) selected",
    "mkt.status_scheduled": "Scheduled",
    "mkt.status_published": "Published",
    "mkt.status_failed": "Failed",
    "mkt.status_publishing": "Publishing",
    "mkt.status_draft": "Draft",
    "mkt.weekdays": "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    "trade_cat.material_pos": "POS Material",
    "trade_cat.degustacao": "Tasting",
    "trade_cat.promocao": "Promotion",
    "trade_cat.bonificacao": "Bonus",
    "trade_cat.logistica": "Logistics",
    "trade_cat.merchandising": "Merchandising",
    "trade_cat.enxoval": "Kit",
    "trade_cat.midia": "Media / Communication",
    "trade_cat.evento": "Event",
    "trade_cat.treinamento": "Training",
    "trade_cat.outros": "Others",
  },
  es: {
    "system.title": "Sistema Huggs",
    "loading": "Cargando...",
    "nav.dashboard": "Panel",
    "nav.notifications": "Notificaciones",
    "nav.audit": "Auditoría",
    "nav.install_app": "Instalar App",
    "nav.settings": "Configuración",
    "nav.logout": "Salir",
    "nav.connected": "Conectado",
    "nav.all_modules": "Todos los Módulos",
    "nav.n_modules": "módulos",
    "lang.label": "Idioma",
    "lang.pt-BR": "Português (BR)",
    "lang.en": "English",
    "lang.es": "Español",
    "lang.ar": "العربية",
    "offline.message": "Estás sin conexión. Algunas funciones pueden estar limitadas. Los datos se sincronizarán cuando vuelvas a estar en línea.",
    "offline.poor": "Conexión inestable detectada. La app intentará reconectar automáticamente.",

    "module.prospects": "Prospectos",
    "module.financeiro": "Financiero",
    "module.marketing": "Marketing",
    "module.trade": "Trade Marketing",
    "module.fabrica": "Fábrica",
    "module.comercial": "Comercial",
    "module.eventos": "Eventos",
    "module.departamentos": "Departamentos",
    "module.precos": "Tablas de Precios",

    "prospects.overview": "Vista General",
    "prospects.list": "Lista de Prospectos",
    "prospects.kanban": "Kanban",
    "prospects.activities": "Actividades",
    "prospects.tasks": "Tareas",
    "prospects.demands": "Central de Demandas",
    "prospects.title": "Prospectos",
    "prospects.registered": "prospectos registrados",
    "prospects.new": "Nuevo Prospecto",
    "prospects.ai": "IA",
    "prospects.search": "Buscar por nombre, email, teléfono...",
    "prospects.filter_status": "Filtrar por estado",
    "prospects.all_status": "Todos los Estados",
    "prospects.update_list": "Actualizar Lista",
    "prospects.none_found": "No se encontraron prospectos",
    "prospects.loading_list": "Cargando prospectos...",

    "status.novo": "Nuevo",
    "status.em_contato": "En Contacto",
    "status.proposta_enviada": "Propuesta",
    "status.negociacao": "Negociación",
    "status.ganho": "Ganado",
    "status.perdido": "Perdido",

    "label.email": "Email",
    "label.phone": "Teléfono",
    "label.seller": "Vendedor",

    "financeiro.overview": "Vista General",
    "financeiro.consolidated": "Dashboard Consolidado",
    "financeiro.dre": "P&L Analítico",
    "financeiro.departments": "Vista por Departamento",
    "financeiro.trade_budget": "Gestión de Presupuestos",
    "financeiro.payments_center": "Central de Pagos",
    "financeiro.dept_approvals": "Aprobaciones Depts",
    "financeiro.payables": "Cuentas por Pagar",
    "financeiro.receivables": "Cuentas por Cobrar",
    "financeiro.cashflow": "Flujo de Caja",
    "financeiro.bank_balances": "Saldos Bancarios",
    "financeiro.chart_accounts": "Plan de Cuentas",
    "financeiro.classify_bank": "Clasificar Banco",

    "trade.admin": "Administrativo",
    "trade.my_team": "Mi Equipo",
    "trade.pdvs": "PDVs",
    "trade.visits": "Visitas",
    "trade.sellout": "Sell Out",
    "trade.shelf": "Medición Estantes",
    "trade.brands": "Nuestras Marcas",
    "trade.photos": "Fotos",
    "trade.ideal_photos": "Fotos Ideales",
    "trade.audit": "Auditoría Góndola",
    "trade.competitive": "Análisis Competitivo",
    "trade.rewards": "Premiaciones",
    "trade.whatsapp": "WhatsApp",
    "trade.ai_insights": "Insights IA",

    "marketing.dashboards": "Dashboards & IA",
    "marketing.overview": "Vista General",

    "fabrica.dashboard": "Dashboard",
    "fabrica.entry": "Entrada",
    "fabrica.nfe": "Recepción NF-e",
    "fabrica.raw_materials": "Materias Primas",
    "fabrica.production": "Producción",
    "fabrica.formulas": "Fórmulas (BOM)",
    "fabrica.planning": "Planificación MRP",
    "fabrica.orders": "Órdenes de Producción",
    "fabrica.tracking": "Registros",
    "fabrica.quality": "Calidad",
    "fabrica.stops": "Paradas",
    "fabrica.resources": "Recursos",
    "fabrica.machines": "Máquinas",
    "fabrica.operators": "Operadores",
    "fabrica.fiscal": "Fiscal",
    "fabrica.tax_table": "Tabla de Impuestos",
    "fabrica.output": "Salida",
    "fabrica.finished": "Productos Terminados",
    "fabrica.review": "Revisión de Fichas",
    "fabrica.tools": "Herramientas",
    "fabrica.agent": "Agente Huggs",
    "fabrica.qa_agent": "Agente de QA",

    "comercial.dashboard": "Dashboard",
    "comercial.launches": "Calendario de Lanzamientos",
    "comercial.ibge": "Datos IBGE",
    "comercial.mining": "Minería de Leads",
    "comercial.reactivation": "Reactivación",
    "comercial.municipalities": "Municipios",
    "comercial.whitespace": "Whitespace",

    "eventos.events": "Eventos",
    "eventos.dashboard": "Dashboard",

    "precos.dashboard": "Dashboard",
    "precos.matrix": "Matriz Comparativa",
    "precos.manage": "Gestionar Tablas",
    "precos.approval": "Aprobación",
    "precos.client_portal": "Portal Cliente",
    "precos.access_control": "Control de Acceso",

    "dept.expenses": "Gastos",
    "dept.dashboard": "Dashboard",

    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Vista general de tu CRM",
    "dashboard.ai_insights": "Insights de IA",
    "dashboard.activities_30d": "Actividades - Últimos 30 Días",
    "dashboard.activities_timeline": "Línea de tiempo de actividades registradas",
    "dashboard.activities_label": "Actividades",

    "widget.total_prospects": "Total de Prospectos",
    "widget.prospects_registered": "Prospectos registrados",
    "widget.in_negotiation": "En Negociación",
    "widget.prospects_negotiation": "Prospectos en negociación",
    "widget.activities_today": "Actividades Hoy",
    "widget.activities_registered": "Actividades registradas",

    "quick.prospects": "Módulo de Prospectos",
    "quick.prospects_desc": "Gestión completa de prospectos y pipeline",
    "quick.trade": "Módulo de Trade Marketing",
    "quick.trade_desc": "Monitoreo de PDVs y rendimiento",
    "quick.financeiro": "Módulo Financiero",
    "quick.financeiro_desc": "Gestión de cuentas y flujo de caja",
    "quick.fabrica": "Módulo Fábrica",
    "quick.fabrica_desc": "Producción, fórmulas y calidad",

    "action.save": "Guardar",
    "action.cancel": "Cancelar",
    "action.delete": "Eliminar",
    "action.edit": "Editar",
    "action.search": "Buscar",
    "action.filter": "Filtrar",
    "action.export": "Exportar",
    "action.refresh": "Actualizar",
    "action.close": "Cerrar",
    "action.confirm": "Confirmar",
    "action.back": "Volver",
    "action.next": "Siguiente",

    "trade_w.active_stores": "PDVs Activos",
    "trade_w.active_stores_desc": "Puntos de venta",
    "trade_w.monthly_visits": "Visitas del Mes",
    "trade_w.monthly_visits_desc": "Visitas realizadas",
    "trade_w.monthly_photos": "Fotos del Mes",
    "trade_w.monthly_photos_desc": "Fotos enviadas",
    "trade_w.investments": "Inversiones",
    "trade_w.investments_desc": "Total del mes",

    "fin_w.payable_pending": "Por Pagar (Pendientes)",
    "fin_w.payable_overdue": "Por Pagar (Vencidas)",
    "fin_w.total_payable": "Total por Pagar",
    "fin_w.payable_overdue_val": "Pagar Vencido",
    "fin_w.receivable_pending": "Por Cobrar (Pendientes)",
    "fin_w.receivable_overdue": "Por Cobrar (Vencidas)",
    "fin_w.total_receivable": "Total por Cobrar",
    "fin_w.receivable_overdue_val": "Cobrar Vencido",
    "fin_w.section_payable": "Cuentas por Pagar",
    "fin_w.section_receivable": "Cuentas por Cobrar",
    "fin_w.titles_due": "Títulos por vencer",
    "fin_w.attention_needed": "Atención necesaria",
    "fin_w.pending_value": "Valor pendiente",
    "fin_w.overdue_value": "Valor en atraso",
    "fin_w.delinquency": "Morosidad",

    "exec.total_prospects": "Total de Prospectos",
    "exec.visits_30d": "Visitas (30 días)",
    "exec.conversion_rate": "Tasa de Conversión",
    "exec.avg_ticket": "Ticket Promedio",
    "exec.active_goals": "Metas Activas",
    "exec.vs_previous": "vs período anterior",

    "funnel.title": "Embudo de Prospección",
    "funnel.description": "Tasa de conversión por etapa",
    "funnel.prospects_label": "Prospectos",
    "funnel.percentage_label": "Porcentaje",

    "brand.total_measurements": "Total Mediciones",
    "brand.measurements_period": "mediciones en el período",
    "brand.avg_share": "Share Promedio",
    "brand.avg_share_desc": "de nuestras marcas",
    "brand.leading_brand": "Marca Líder",
    "brand.leading_brand_desc": "mayor espacio ocupado",
    "brand.growth": "Crecimiento",
    "brand.growth_desc": "vs. período anterior",
    "brand.distribution": "Distribución por Marca",
    "brand.monthly_evolution": "Evolución Mensual por Marca",
    "brand.store_ranking": "Ranking de Tiendas por Share",
    "brand.measurements": "mediciones",
    "brand.no_data": "Sin datos para mostrar",

    "trade_exec.active_stores": "PDVs Activos",
    "trade_exec.monthly_visits": "Visitas del Mes",
    "trade_exec.monthly_photos": "Fotos del Mes",
    "trade_exec.avg_roi": "ROI Promedio",
    "trade_exec.top_clients": "Top 10 Clientes por Lanzamientos",
    "trade_exec.total_value": "Valor Total",
    "trade_exec.no_entries": "No se encontraron lanzamientos",
    "trade_exec.recent_photos": "Fotos Recientes",
    "trade_exec.pending": "Pendiente",
    "trade_exec.no_photos": "No se encontraron fotos",

    "approval.total_pending": "Total Pendiente",
    "approval.campaigns": "Campañas",
    "approval.entries": "Lanzamientos",
    "approval.total_value": "Valor Total",
    "approval.status": "Estado",
    "approval.review": "Revisar",
    "approval.up_to_date": "Al día ✓",

    "comercial.untapped": "Potencial No Explorado",
    "comercial.no_purchase": "clientes registrados sin compras",

    "logout.title": "Sesión cerrada",
    "logout.description": "¡Hasta pronto!",

    "fin.avg_payment_term": "Plazo Medio de Pago",
    "fin.avg_payment_desc": "Media entre emisión y pago",
    "fin.punctuality_index": "Índice de Puntualidad",
    "fin.paid_on_time": "Pagados a tiempo o antes",
    "fin.current_month": "Mes Actual",
    "fin.vs_prev_month": "vs mes anterior",
    "fin.no_variation": "Sin variación",
    "fin.next_30_days": "Próximos 30 días",
    "fin.due_in_period": "A vencer en el período",
    "fin.due_today": "Vencen Hoy",
    "fin.titles": "títulos",
    "fin.next_7_days": "Próximos 7 Días",
    "fin.overdue_30d": "Vencidas +30 días",
    "fin.monthly_evolution": "Evolución Mensual",
    "fin.payments_vs_pending": "Pagos realizados vs pendientes",
    "fin.area": "Área",
    "fin.bars": "Barras",
    "fin.lines": "Líneas",
    "fin.paid": "Pagado",
    "fin.pending": "Pendiente",
    "fin.by_department": "Por Departamento",
    "fin.expense_distribution": "Distribución de gastos",
    "fin.by_status": "Por Estado",
    "fin.title_status": "Situación de títulos",
    "fin.top10_suppliers": "Top 10 Proveedores",
    "fin.by_total_value": "Por valor total",
    "fin.loading_data": "Cargando datos consolidados...",
    "fin.days": "días",
    "fin.avg_receipt_term": "Plazo Medio de Cobro",
    "fin.avg_receipt_desc": "Media entre emisión y cobro",
    "fin.received_on_time": "Cobrados a tiempo o antes",
    "fin.to_receive_period": "A cobrar en el período",
    "fin.received": "Cobrado",
    "fin.receipts_vs_pending": "Cobros realizados vs pendientes",
    "fin.top10_clients_open": "Top 10 Clientes (abierto)",
    "fin.highest_receivable": "Mayores valores a cobrar",
    "fin.receivable_by_term": "A Cobrar por Plazo",
    "fin.distribution_by_term": "Distribución por rango de vencimiento",
    "fin.status_distribution": "Distribución por Estado",
    "fin.value_by_status": "Proporción de valores por situación",
    "fin.cashflow_events": "Flujo de Caja Eventos",
    "fin.cashflow_dept": "Flujo de Caja",
    "fin.last_6_months": "Últimos 6 meses",
    "fin.inflows": "Entradas",
    "fin.outflows": "Salidas",
    "fin.balance": "Saldo",
    "fin.accumulated_balance": "Saldo Acumulado",
    "fin.event_budgets": "Presupuestos de Eventos",
    "fin.dept_budgets": "Presupuestos del Departamento",
    "fin.view_all_budgets": "Ver todos los presupuestos",
    "fin.total_budgeted": "Total Presupuestado",
    "fin.used": "Utilizado",
    "fin.available": "Disponible",
    "fin.utilization": "Utilización",
    "fin.no_budgets_found": "No se encontraron presupuestos",
    "fin.no_event_budgets": "No se encontraron presupuestos de eventos",
    "trade_fin.title": "Financiero Trade Marketing",
    "trade_fin.subtitle": "Gestión de presupuestos, inversiones y plan de cuentas",
    "trade_fin.full_module": "Módulo Financiero Completo",
    "trade_fin.dashboard": "Dashboard Financiero",
    "trade_fin.dashboard_desc": "Vista consolidada de presupuestos y campañas",
    "trade_fin.my_statement": "Mi Extracto",
    "trade_fin.statement_desc": "Historial de lanzamientos y aprobaciones",
    "trade_fin.campaigns": "Campañas",
    "trade_fin.campaigns_desc": "Gestión administrativa de campañas",
    "trade_fin.entries_panel": "Panel de Lanzamientos",
    "trade_fin.entries_desc": "Resultados y ejecución de campañas",
    "trade_fin.current_accounts": "Cuentas Corrientes",
    "trade_fin.current_desc": "Gestión de cuentas corrientes por cliente",
    "trade_fin.semester_budgets": "Presupuestos Semestrales",
    "trade_fin.semester_desc": "Planificación y seguimiento semestral",
    "trade_fin.entries": "Lanzamientos",
    "trade_fin.entries_all_desc": "Todos los lanzamientos financieros",
    "trade_fin.approvals": "Aprobaciones",
    "trade_fin.approvals_desc": "Revisar y aprobar lanzamientos pendientes",
    "trade_fin.payables": "Cuentas por Pagar",
    "trade_fin.payables_desc": "Gestión de cuentas y presupuestos",
    "trade_fin.search_client": "Buscar Cliente",
    "trade_fin.search_placeholder": "Escriba nombre, código, CNPJ, ciudad o dirección...",
    "trade_fin.smart_filter": "Filtro Inteligente (IA)",
    "trade_fin.clear": "Limpiar",
    "trade_fin.no_client_found": "Ningún cliente encontrado",
    "mkt.title": "Marketing",
    "mkt.subtitle": "Reportes y dashboards integrados",
    "mkt.back_menu": "Volver al Menú",
    "mkt.mission_control": "Mission Control",
    "mkt.mission_desc": "Central de tareas de marketing para lanzamientos",
    "mkt.instagram_desc": "Análisis y métricas de Instagram",
    "mkt.dashcortex_desc": "Reportes integrados DashCortex",
    "mkt.powerbi_desc": "Dashboards y visualizaciones Power BI",
    "mkt.social": "Redes Sociales",
    "mkt.social_desc": "Gestionar cuentas y métricas sociales",
    "mkt.elevenlabs_desc": "Audio, voz y música con IA",
    "mkt.access": "Acceder",
    "mkt.new": "NUEVO",
    "mkt.followers_evolution": "Evolución de Seguidores",
    "mkt.followers": "Seguidores",
    "mkt.engagement_reach": "Engagement & Alcance",
    "mkt.engagement_pct": "Engagement %",
    "mkt.reach": "Alcance",
    "mkt.publications": "Publicaciones",
    "mkt.editorial_calendar": "Calendario Editorial",
    "mkt.today": "Hoy",
    "mkt.more": "más",
    "mkt.posts_of": "Posts de",
    "mkt.no_posts_day": "No hay posts programados para este día",
    "mkt.media_count": "medio(s)",
    "mkt.accounts_selected": "cuenta(s) seleccionada(s)",
    "mkt.status_scheduled": "Programado",
    "mkt.status_published": "Publicado",
    "mkt.status_failed": "Falló",
    "mkt.status_publishing": "Publicando",
    "mkt.status_draft": "Borrador",
    "mkt.weekdays": "Dom,Lun,Mar,Mié,Jue,Vie,Sáb",
    "trade_cat.material_pos": "Material POS",
    "trade_cat.degustacao": "Degustación",
    "trade_cat.promocao": "Promoción",
    "trade_cat.bonificacao": "Bonificación",
    "trade_cat.logistica": "Logística",
    "trade_cat.merchandising": "Merchandising",
    "trade_cat.enxoval": "Ajuar",
    "trade_cat.midia": "Medios / Comunicación",
    "trade_cat.evento": "Evento",
    "trade_cat.treinamento": "Capacitación",
    "trade_cat.outros": "Otros",
  },
  ar: {
    "system.title": "نظام هاغز",
    "loading": "جاري التحميل...",
    "nav.dashboard": "لوحة التحكم",
    "nav.notifications": "الإشعارات",
    "nav.audit": "التدقيق",
    "nav.install_app": "تثبيت التطبيق",
    "nav.settings": "الإعدادات",
    "nav.logout": "خروج",
    "nav.connected": "متصل",
    "nav.all_modules": "جميع الوحدات",
    "nav.n_modules": "وحدات",
    "lang.label": "اللغة",
    "lang.pt-BR": "Português (BR)",
    "lang.en": "English",
    "lang.es": "Español",
    "lang.ar": "العربية",
    "offline.message": "أنت غير متصل. قد تكون بعض الميزات محدودة. ستتم مزامنة البيانات عند العودة للاتصال.",
    "offline.poor": "تم اكتشاف اتصال غير مستقر. سيحاول التطبيق إعادة الاتصال تلقائياً.",

    "module.prospects": "العملاء المحتملون",
    "module.financeiro": "المالية",
    "module.marketing": "التسويق",
    "module.trade": "تسويق التجارة",
    "module.fabrica": "المصنع",
    "module.comercial": "التجاري",
    "module.eventos": "الفعاليات",
    "module.departamentos": "الأقسام",
    "module.precos": "جداول الأسعار",

    "prospects.overview": "نظرة عامة",
    "prospects.list": "قائمة العملاء المحتملين",
    "prospects.kanban": "كانبان",
    "prospects.activities": "الأنشطة",
    "prospects.tasks": "المهام",
    "prospects.demands": "مركز الطلبات",
    "prospects.title": "العملاء المحتملون",
    "prospects.registered": "عملاء محتملون مسجلون",
    "prospects.new": "عميل محتمل جديد",
    "prospects.ai": "ذكاء اصطناعي",
    "prospects.search": "البحث بالاسم، البريد، الهاتف...",
    "prospects.filter_status": "تصفية حسب الحالة",
    "prospects.all_status": "جميع الحالات",
    "prospects.update_list": "تحديث القائمة",
    "prospects.none_found": "لم يتم العثور على عملاء محتملين",
    "prospects.loading_list": "جاري تحميل العملاء المحتملين...",

    "status.novo": "جديد",
    "status.em_contato": "قيد التواصل",
    "status.proposta_enviada": "عرض مقدم",
    "status.negociacao": "تفاوض",
    "status.ganho": "مكسوب",
    "status.perdido": "خسارة",

    "label.email": "البريد الإلكتروني",
    "label.phone": "الهاتف",
    "label.seller": "البائع",

    "financeiro.overview": "نظرة عامة",
    "financeiro.consolidated": "لوحة تحكم موحدة",
    "financeiro.dre": "قائمة الدخل التحليلية",
    "financeiro.departments": "عرض الأقسام",
    "financeiro.trade_budget": "إدارة الميزانيات",
    "financeiro.payments_center": "مركز المدفوعات",
    "financeiro.dept_approvals": "موافقات الأقسام",
    "financeiro.payables": "حسابات دائنة",
    "financeiro.receivables": "حسابات مدينة",
    "financeiro.cashflow": "التدفق النقدي",
    "financeiro.bank_balances": "أرصدة بنكية",
    "financeiro.chart_accounts": "دليل الحسابات",
    "financeiro.classify_bank": "تصنيف بنكي",

    "trade.admin": "إداري",
    "trade.my_team": "فريقي",
    "trade.pdvs": "نقاط البيع",
    "trade.visits": "الزيارات",
    "trade.sellout": "المبيعات",
    "trade.shelf": "قياس الرفوف",
    "trade.brands": "علاماتنا التجارية",
    "trade.photos": "الصور",
    "trade.ideal_photos": "صور مثالية",
    "trade.audit": "تدقيق الرفوف",
    "trade.competitive": "تحليل تنافسي",
    "trade.rewards": "المكافآت",
    "trade.whatsapp": "واتساب",
    "trade.ai_insights": "رؤى الذكاء الاصطناعي",

    "marketing.dashboards": "لوحات التحكم والذكاء الاصطناعي",
    "marketing.overview": "نظرة عامة",

    "fabrica.dashboard": "لوحة التحكم",
    "fabrica.entry": "الاستلام",
    "fabrica.nfe": "استلام الفواتير",
    "fabrica.raw_materials": "المواد الخام",
    "fabrica.production": "الإنتاج",
    "fabrica.formulas": "التركيبات",
    "fabrica.planning": "تخطيط MRP",
    "fabrica.orders": "أوامر الإنتاج",
    "fabrica.tracking": "التسجيل",
    "fabrica.quality": "الجودة",
    "fabrica.stops": "التوقفات",
    "fabrica.resources": "الموارد",
    "fabrica.machines": "الآلات",
    "fabrica.operators": "المشغلون",
    "fabrica.fiscal": "الضريبي",
    "fabrica.tax_table": "جدول الضرائب",
    "fabrica.output": "المخرجات",
    "fabrica.finished": "منتجات جاهزة",
    "fabrica.review": "مراجعة البطاقات",
    "fabrica.tools": "أدوات",
    "fabrica.agent": "وكيل هاغز",
    "fabrica.qa_agent": "وكيل الجودة",

    "comercial.dashboard": "لوحة التحكم",
    "comercial.launches": "تقويم الإطلاقات",
    "comercial.ibge": "بيانات IBGE",
    "comercial.mining": "تعدين العملاء",
    "comercial.reactivation": "إعادة التنشيط",
    "comercial.municipalities": "البلديات",
    "comercial.whitespace": "المساحة البيضاء",

    "eventos.events": "الفعاليات",
    "eventos.dashboard": "لوحة التحكم",

    "precos.dashboard": "لوحة التحكم",
    "precos.matrix": "مصفوفة مقارنة",
    "precos.manage": "إدارة الجداول",
    "precos.approval": "الموافقة",
    "precos.client_portal": "بوابة العميل",
    "precos.access_control": "التحكم بالوصول",

    "dept.expenses": "المصروفات",
    "dept.dashboard": "لوحة التحكم",

    "dashboard.title": "لوحة التحكم",
    "dashboard.subtitle": "نظرة عامة على نظام إدارة العلاقات",
    "dashboard.ai_insights": "رؤى الذكاء الاصطناعي",
    "dashboard.activities_30d": "الأنشطة - آخر 30 يوم",
    "dashboard.activities_timeline": "الجدول الزمني للأنشطة المسجلة",
    "dashboard.activities_label": "الأنشطة",

    "widget.total_prospects": "إجمالي العملاء المحتملين",
    "widget.prospects_registered": "عملاء محتملون مسجلون",
    "widget.in_negotiation": "قيد التفاوض",
    "widget.prospects_negotiation": "عملاء محتملون في مرحلة التفاوض",
    "widget.activities_today": "أنشطة اليوم",
    "widget.activities_registered": "أنشطة مسجلة",

    "quick.prospects": "وحدة العملاء المحتملين",
    "quick.prospects_desc": "إدارة كاملة للعملاء المحتملين",
    "quick.trade": "وحدة تسويق التجارة",
    "quick.trade_desc": "مراقبة نقاط البيع والأداء",
    "quick.financeiro": "الوحدة المالية",
    "quick.financeiro_desc": "إدارة الحسابات والتدفق النقدي",
    "quick.fabrica": "وحدة المصنع",
    "quick.fabrica_desc": "الإنتاج والتركيبات والجودة",

    "action.save": "حفظ",
    "action.cancel": "إلغاء",
    "action.delete": "حذف",
    "action.edit": "تعديل",
    "action.search": "بحث",
    "action.filter": "تصفية",
    "action.export": "تصدير",
    "action.refresh": "تحديث",
    "action.close": "إغلاق",
    "action.confirm": "تأكيد",
    "action.back": "رجوع",
    "action.next": "التالي",

    "trade_w.active_stores": "نقاط البيع النشطة",
    "trade_w.active_stores_desc": "نقاط البيع",
    "trade_w.monthly_visits": "زيارات الشهر",
    "trade_w.monthly_visits_desc": "الزيارات المنجزة",
    "trade_w.monthly_photos": "صور الشهر",
    "trade_w.monthly_photos_desc": "الصور المرسلة",
    "trade_w.investments": "الاستثمارات",
    "trade_w.investments_desc": "إجمالي الشهر",

    "fin_w.payable_pending": "مستحقة (معلقة)",
    "fin_w.payable_overdue": "مستحقة (متأخرة)",
    "fin_w.total_payable": "إجمالي المستحقات",
    "fin_w.payable_overdue_val": "مستحقات متأخرة",
    "fin_w.receivable_pending": "مدينة (معلقة)",
    "fin_w.receivable_overdue": "مدينة (متأخرة)",
    "fin_w.total_receivable": "إجمالي المدينة",
    "fin_w.receivable_overdue_val": "مدينة متأخرة",
    "fin_w.section_payable": "حسابات دائنة",
    "fin_w.section_receivable": "حسابات مدينة",
    "fin_w.titles_due": "سندات مستحقة",
    "fin_w.attention_needed": "يحتاج انتباه",
    "fin_w.pending_value": "قيمة معلقة",
    "fin_w.overdue_value": "قيمة متأخرة",
    "fin_w.delinquency": "تعثر",

    "exec.total_prospects": "إجمالي العملاء المحتملين",
    "exec.visits_30d": "الزيارات (30 يوم)",
    "exec.conversion_rate": "معدل التحويل",
    "exec.avg_ticket": "متوسط التذكرة",
    "exec.active_goals": "الأهداف النشطة",
    "exec.vs_previous": "مقارنة بالفترة السابقة",

    "funnel.title": "قمع التنقيب",
    "funnel.description": "معدل التحويل حسب المرحلة",
    "funnel.prospects_label": "العملاء المحتملون",
    "funnel.percentage_label": "النسبة المئوية",

    "brand.total_measurements": "إجمالي القياسات",
    "brand.measurements_period": "قياسات في الفترة",
    "brand.avg_share": "متوسط الحصة",
    "brand.avg_share_desc": "لعلاماتنا التجارية",
    "brand.leading_brand": "العلامة الرائدة",
    "brand.leading_brand_desc": "أكبر مساحة رف",
    "brand.growth": "النمو",
    "brand.growth_desc": "مقارنة بالفترة السابقة",
    "brand.distribution": "التوزيع حسب العلامة",
    "brand.monthly_evolution": "التطور الشهري حسب العلامة",
    "brand.store_ranking": "ترتيب المتاجر حسب الحصة",
    "brand.measurements": "قياسات",
    "brand.no_data": "لا توجد بيانات للعرض",

    "trade_exec.active_stores": "نقاط البيع النشطة",
    "trade_exec.monthly_visits": "زيارات الشهر",
    "trade_exec.monthly_photos": "صور الشهر",
    "trade_exec.avg_roi": "متوسط العائد",
    "trade_exec.top_clients": "أفضل 10 عملاء حسب الإدخالات",
    "trade_exec.total_value": "القيمة الإجمالية",
    "trade_exec.no_entries": "لم يتم العثور على إدخالات",
    "trade_exec.recent_photos": "صور حديثة",
    "trade_exec.pending": "معلق",
    "trade_exec.no_photos": "لم يتم العثور على صور",

    "approval.total_pending": "إجمالي المعلق",
    "approval.campaigns": "الحملات",
    "approval.entries": "الإدخالات",
    "approval.total_value": "القيمة الإجمالية",
    "approval.status": "الحالة",
    "approval.review": "مراجعة",
    "approval.up_to_date": "محدّث ✓",

    "comercial.untapped": "إمكانات غير مستغلة",
    "comercial.no_purchase": "عملاء مسجلون بدون مشتريات",

    "logout.title": "تم تسجيل الخروج",
    "logout.description": "إلى اللقاء!",

    "fin.avg_payment_term": "متوسط مدة الدفع",
    "fin.avg_payment_desc": "المتوسط بين الإصدار والدفع",
    "fin.punctuality_index": "مؤشر الالتزام",
    "fin.paid_on_time": "مدفوعة في الوقت أو قبله",
    "fin.current_month": "الشهر الحالي",
    "fin.vs_prev_month": "مقارنة بالشهر السابق",
    "fin.no_variation": "بدون تغيير",
    "fin.next_30_days": "الـ 30 يوم القادمة",
    "fin.due_in_period": "مستحقة في الفترة",
    "fin.due_today": "مستحقة اليوم",
    "fin.titles": "سندات",
    "fin.next_7_days": "الـ 7 أيام القادمة",
    "fin.overdue_30d": "متأخرة +30 يوم",
    "fin.monthly_evolution": "التطور الشهري",
    "fin.payments_vs_pending": "المدفوعات مقابل المعلقة",
    "fin.area": "مساحة",
    "fin.bars": "أعمدة",
    "fin.lines": "خطوط",
    "fin.paid": "مدفوع",
    "fin.pending": "معلق",
    "fin.by_department": "حسب القسم",
    "fin.expense_distribution": "توزيع المصروفات",
    "fin.by_status": "حسب الحالة",
    "fin.title_status": "حالة السندات",
    "fin.top10_suppliers": "أفضل 10 موردين",
    "fin.by_total_value": "حسب القيمة الإجمالية",
    "fin.loading_data": "جاري تحميل البيانات الموحدة...",
    "fin.days": "أيام",
    "fin.avg_receipt_term": "متوسط مدة التحصيل",
    "fin.avg_receipt_desc": "المتوسط بين الإصدار والتحصيل",
    "fin.received_on_time": "محصلة في الوقت أو قبله",
    "fin.to_receive_period": "للتحصيل في الفترة",
    "fin.received": "محصّل",
    "fin.receipts_vs_pending": "التحصيلات مقابل المعلقة",
    "fin.top10_clients_open": "أفضل 10 عملاء (مفتوح)",
    "fin.highest_receivable": "أعلى قيم للتحصيل",
    "fin.receivable_by_term": "التحصيل حسب المدة",
    "fin.distribution_by_term": "التوزيع حسب فترة الاستحقاق",
    "fin.status_distribution": "التوزيع حسب الحالة",
    "fin.value_by_status": "نسبة القيم حسب الحالة",
    "fin.cashflow_events": "التدفق النقدي للفعاليات",
    "fin.cashflow_dept": "التدفق النقدي",
    "fin.last_6_months": "آخر 6 أشهر",
    "fin.inflows": "المدخلات",
    "fin.outflows": "المخرجات",
    "fin.balance": "الرصيد",
    "fin.accumulated_balance": "الرصيد التراكمي",
    "fin.event_budgets": "ميزانيات الفعاليات",
    "fin.dept_budgets": "ميزانيات القسم",
    "fin.view_all_budgets": "عرض جميع الميزانيات",
    "fin.total_budgeted": "إجمالي الميزانية",
    "fin.used": "مستخدم",
    "fin.available": "متاح",
    "fin.utilization": "الاستخدام",
    "fin.no_budgets_found": "لم يتم العثور على ميزانيات",
    "fin.no_event_budgets": "لم يتم العثور على ميزانيات فعاليات",
    "trade_fin.title": "مالية تسويق التجارة",
    "trade_fin.subtitle": "إدارة الميزانيات والاستثمارات ودليل الحسابات",
    "trade_fin.full_module": "الوحدة المالية الكاملة",
    "trade_fin.dashboard": "لوحة التحكم المالية",
    "trade_fin.dashboard_desc": "عرض موحد للميزانيات والحملات",
    "trade_fin.my_statement": "كشف حسابي",
    "trade_fin.statement_desc": "سجل الإدخالات والموافقات",
    "trade_fin.campaigns": "الحملات",
    "trade_fin.campaigns_desc": "إدارة الحملات",
    "trade_fin.entries_panel": "لوحة الإدخالات",
    "trade_fin.entries_desc": "نتائج وتنفيذ الحملات",
    "trade_fin.current_accounts": "الحسابات الجارية",
    "trade_fin.current_desc": "إدارة الحسابات الجارية حسب العميل",
    "trade_fin.semester_budgets": "ميزانيات نصف سنوية",
    "trade_fin.semester_desc": "التخطيط والمتابعة نصف السنوية",
    "trade_fin.entries": "الإدخالات",
    "trade_fin.entries_all_desc": "جميع الإدخالات المالية",
    "trade_fin.approvals": "الموافقات",
    "trade_fin.approvals_desc": "مراجعة والموافقة على الإدخالات المعلقة",
    "trade_fin.payables": "حسابات دائنة",
    "trade_fin.payables_desc": "إدارة الحسابات والميزانيات",
    "trade_fin.search_client": "بحث عن عميل",
    "trade_fin.search_placeholder": "اكتب الاسم، الرمز، CNPJ، المدينة أو العنوان...",
    "trade_fin.smart_filter": "فلتر ذكي (ذكاء اصطناعي)",
    "trade_fin.clear": "مسح",
    "trade_fin.no_client_found": "لم يتم العثور على عميل",
    "mkt.title": "التسويق",
    "mkt.subtitle": "تقارير ولوحات تحكم متكاملة",
    "mkt.back_menu": "العودة للقائمة",
    "mkt.mission_control": "مركز المهام",
    "mkt.mission_desc": "مركز مهام التسويق للإطلاقات",
    "mkt.instagram_desc": "تحليلات ومقاييس إنستغرام",
    "mkt.dashcortex_desc": "تقارير DashCortex المتكاملة",
    "mkt.powerbi_desc": "لوحات تحكم وتصورات Power BI",
    "mkt.social": "وسائل التواصل",
    "mkt.social_desc": "إدارة حسابات ومقاييس التواصل",
    "mkt.elevenlabs_desc": "صوت وموسيقى بالذكاء الاصطناعي",
    "mkt.access": "دخول",
    "mkt.new": "جديد",
    "mkt.followers_evolution": "تطور المتابعين",
    "mkt.followers": "المتابعون",
    "mkt.engagement_reach": "التفاعل والوصول",
    "mkt.engagement_pct": "التفاعل %",
    "mkt.reach": "الوصول",
    "mkt.publications": "المنشورات",
    "mkt.editorial_calendar": "التقويم التحريري",
    "mkt.today": "اليوم",
    "mkt.more": "المزيد",
    "mkt.posts_of": "منشورات",
    "mkt.no_posts_day": "لا توجد منشورات مجدولة لهذا اليوم",
    "mkt.media_count": "وسائط",
    "mkt.accounts_selected": "حساب(ات) محددة",
    "mkt.status_scheduled": "مجدول",
    "mkt.status_published": "منشور",
    "mkt.status_failed": "فشل",
    "mkt.status_publishing": "جاري النشر",
    "mkt.status_draft": "مسودة",
    "mkt.weekdays": "أحد,إثن,ثلا,أرب,خمي,جمع,سبت",
    "trade_cat.material_pos": "مواد نقاط البيع",
    "trade_cat.degustacao": "تذوق",
    "trade_cat.promocao": "ترويج",
    "trade_cat.bonificacao": "مكافأة",
    "trade_cat.logistica": "لوجستيات",
    "trade_cat.merchandising": "تسويق بصري",
    "trade_cat.enxoval": "طقم",
    "trade_cat.midia": "إعلام / اتصال",
    "trade_cat.evento": "فعالية",
    "trade_cat.treinamento": "تدريب",
    "trade_cat.outros": "أخرى",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "pt-BR";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["pt-BR"]?.[key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
