// supabase/functions/notion-export-briefing/index.ts
// Upserts a briefing into the user's Notion workspace.
// - Idempotently provisions the "Briefings bimaster" database
// - Patches the database schema if it's missing required properties
// - If briefing.notion_page_id exists and is still valid: PATCH properties and
//   replace the mirror children (preserving the user's free zone)
// - Otherwise creates a new page and stores its id on briefings.notion_page_id
//
// Backwards-compatible contract:
//   request:  { briefing_id, bimaster_origin? }
//   response: { ok, page_id, page_url, database_url }
// Plus new optional fields: { action: 'create'|'update', remote_changes_detected?: boolean }
import { z } from "https://esm.sh/zod@3.23.8";
import { createClient } from "npm:@supabase/supabase-js@2";
import { secureHandler } from "../_shared/secure-handler.ts";
import { getCorsHeaders } from "../_shared/cors.ts";
import { resolveBriefingSla } from "../_shared/briefing-sla.ts";
import {
  appendChildrenInChunks,
  deleteBlocks,
  listAllChildren,
  notion,
  sha256Hex,
  type NotionPage,
} from "../_shared/notion-client.ts";
import {
  buildBriefingBlocks,
  buildDatabaseSchema,
  buildPageProperties,
  FREE_ZONE_START_LABEL,
} from "./blocks.ts";

const DATABASE_NAME = "Briefings bimaster";

const BodySchema = z.object({
  briefing_id: z.string().uuid(),
  bimaster_origin: z.string().url().optional(),
  /** When true, push even if remote was edited after our last push. */
  force: z.boolean().optional().default(false),
  /** When true, include cofre documents (signed URLs) in the mirror. */
  incluir_documentos: z.boolean().optional().default(true),
  /** When true, only documents not yet sent (or updated since) are pushed; others are still listed. */
  apenas_novos_documentos: z.boolean().optional().default(false),
}).strict();

async function findExistingDatabase(token: string): Promise<{ id: string; url: string } | null> {
  const r = await notion<{ results: Array<{ id: string; url: string; title: Array<{ plain_text: string }> }> }>(
    token,
    "/search",
    {
      method: "POST",
      body: JSON.stringify({
        query: DATABASE_NAME,
        filter: { value: "database", property: "object" },
        page_size: 20,
      }),
    },
  );
  if (!r.ok || !r.data) return null;
  for (const db of r.data.results) {
    const title = db.title?.map((t) => t.plain_text).join("") ?? "";
    if (title.trim().toLowerCase() === DATABASE_NAME.toLowerCase()) {
      return { id: db.id, url: db.url };
    }
  }
  return null;
}

async function findParentPage(token: string): Promise<string | null> {
  const r = await notion<{ results: Array<{ id: string; object: string }> }>(
    token,
    "/search",
    {
      method: "POST",
      body: JSON.stringify({
        filter: { value: "page", property: "object" },
        page_size: 1,
      }),
    },
  );
  if (!r.ok || !r.data?.results?.length) return null;
  return r.data.results[0].id;
}

async function ensureDatabaseSchema(token: string, dbId: string): Promise<void> {
  const r = await notion<{ properties: Record<string, unknown> }>(token, `/databases/${dbId}`);
  if (!r.ok || !r.data) return;
  const existing = new Set(Object.keys(r.data.properties));
  const desired = buildDatabaseSchema();
  const missing: Record<string, unknown> = {};
  for (const [key, def] of Object.entries(desired)) {
    if (key === "Título") continue; // never replace title
    if (!existing.has(key)) missing[key] = def;
  }
  if (Object.keys(missing).length === 0) return;
  await notion(token, `/databases/${dbId}`, {
    method: "PATCH",
    body: JSON.stringify({ properties: missing }),
  });
}

async function createDatabase(
  token: string,
  parentPageId: string,
): Promise<{ id: string; url: string } | null> {
  const r = await notion<{ id: string; url: string }>(token, "/databases", {
    method: "POST",
    body: JSON.stringify({
      parent: { type: "page_id", page_id: parentPageId },
      title: [{ type: "text", text: { content: DATABASE_NAME } }],
      properties: buildDatabaseSchema(),
    }),
  });
  if (!r.ok || !r.data) return null;
  return { id: r.data.id, url: r.data.url };
}

/**
 * Identifies the "mirror" block ids — everything before the free zone heading.
 * The free zone starts at heading_3 with text === FREE_ZONE_START_LABEL.
 * We delete only the mirror blocks, preserving anything the user typed inside
 * the free zone (between that heading and the final divider).
 *
 * Falls back to deleting all children if the marker is missing (legacy pages
 * generated by the previous version of this function).
 */
function pickMirrorBlockIds(children: Array<{ id?: string; type?: string; heading_3?: { rich_text?: Array<{ plain_text?: string }> } }>): string[] {
  const ids: string[] = [];
  let foundMarker = false;
  for (const c of children) {
    if (
      c.type === "heading_3" &&
      (c.heading_3?.rich_text?.[0]?.plain_text ?? "").trim() === FREE_ZONE_START_LABEL
    ) {
      foundMarker = true;
      // Drop the marker too — buildBriefingBlocks will recreate it.
      if (c.id) ids.push(c.id);
      break;
    }
    if (c.id) ids.push(c.id);
  }
  if (!foundMarker) {
    // Legacy page: wipe everything so footer / marker get recreated cleanly.
    return children.map((c) => c.id).filter((x): x is string => !!x);
  }
  return ids;
}

Deno.serve(
  secureHandler(
    { auth: "jwt", rateLimit: 20, rateLimitPrefix: "notion-export-briefing" },
    async (req, ctx) => {
      const cors = getCorsHeaders(req);

      const parsed = BodySchema.safeParse(await req.json().catch(() => ({})));
      if (!parsed.success) {
        return new Response(
          JSON.stringify({ error: parsed.error.flatten() }),
          { status: 400, headers: { ...cors, "Content-Type": "application/json" } },
        );
      }
      const { briefing_id, bimaster_origin, force } = parsed.data;

      const sb = createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
      );

      // 1. Load connection
      const { data: connection, error: connErr } = await sb
        .from("notion_connections")
        .select("*")
        .eq("user_id", ctx.userId)
        .order("updated_at", { ascending: false })
        .limit(1)
        .maybeSingle();

      if (connErr || !connection) {
        return new Response(
          JSON.stringify({ error: "not_connected" }),
          { status: 412, headers: { ...cors, "Content-Type": "application/json" } },
        );
      }

      // 2. Load briefing (owner check)
      const { data: briefing, error: briefingErr } = await sb
        .from("briefings")
        .select(
          "id, user_id, titulo, codigo, tipo, status, completude, payload, projeto_id, template_id, created_at, updated_at, notion_page_id, notion_page_url, notion_last_push_at, notion_page_hash",
        )
        .eq("id", briefing_id)
        .single();

      if (briefingErr || !briefing) {
        return new Response(
          JSON.stringify({ error: "briefing_not_found" }),
          { status: 404, headers: { ...cors, "Content-Type": "application/json" } },
        );
      }
      if (briefing.user_id !== ctx.userId) {
        return new Response(
          JSON.stringify({ error: "forbidden" }),
          { status: 403, headers: { ...cors, "Content-Type": "application/json" } },
        );
      }

      // 3. Template sections
      let sections: Array<{ key: string; label: string; required?: boolean }> = [];
      if (briefing.template_id) {
        const { data: tpl } = await sb
          .from("briefing_templates")
          .select("sections")
          .eq("id", briefing.template_id)
          .maybeSingle();
        if (tpl?.sections && Array.isArray(tpl.sections)) {
          sections = tpl.sections as typeof sections;
        }
      }
      if (sections.length === 0 && briefing.payload && typeof briefing.payload === "object") {
        sections = Object.keys(briefing.payload as Record<string, unknown>).map((k) => ({
          key: k,
          label: k.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
        }));
      }

      // 4. Author + project
      const { data: profile } = await sb
        .from("profiles")
        .select("nome_completo, email")
        .eq("id", briefing.user_id)
        .maybeSingle();

      let projetoNome: string | null = null;
      if (briefing.projeto_id) {
        const { data: proj } = await sb
          .from("projetos")
          .select("nome")
          .eq("id", briefing.projeto_id)
          .maybeSingle();
        projetoNome = proj?.nome ?? null;
      }

      // 5. SLA
      const sla = resolveBriefingSla(briefing.payload);

      // 6. Ensure database exists with full schema
      const token = connection.access_token as string;
      let dbId = connection.briefings_database_id as string | null;
      let dbUrl = connection.briefings_database_url as string | null;

      if (!dbId) {
        const existing = await findExistingDatabase(token);
        if (existing) {
          dbId = existing.id;
          dbUrl = existing.url;
        } else {
          let parentPageId = connection.parent_page_id as string | null;
          if (!parentPageId) parentPageId = await findParentPage(token);
          if (!parentPageId) {
            return new Response(
              JSON.stringify({
                error: "no_accessible_page",
                message:
                  "Compartilhe ao menos uma página com a integração no Notion e tente novamente.",
              }),
              { status: 422, headers: { ...cors, "Content-Type": "application/json" } },
            );
          }
          const created = await createDatabase(token, parentPageId);
          if (!created) {
            return new Response(
              JSON.stringify({ error: "database_create_failed" }),
              { status: 502, headers: { ...cors, "Content-Type": "application/json" } },
            );
          }
          dbId = created.id;
          dbUrl = created.url;
          await sb
            .from("notion_connections")
            .update({ parent_page_id: parentPageId })
            .eq("id", connection.id);
        }
        await sb
          .from("notion_connections")
          .update({
            briefings_database_id: dbId,
            briefings_database_url: dbUrl,
          })
          .eq("id", connection.id);
      }

      await ensureDatabaseSchema(token, dbId!);

      // 7. Build properties + blocks
      // Sempre força o domínio público canônico, ignorando origens de preview/Lovable.
      const PUBLIC_ORIGIN_ALLOWLIST = new Set([
        "https://china.bimaster.online",
        "https://www.bimaster.online",
        "https://bimaster.online",
      ]);
      const requested = bimaster_origin?.replace(/\/$/, "") ?? "";
      const origin = PUBLIC_ORIGIN_ALLOWLIST.has(requested)
        ? requested
        : "https://china.bimaster.online";
      const blocksInput = {
        briefing: {
          titulo: briefing.titulo,
          codigo: briefing.codigo,
          tipo: briefing.tipo,
          status: briefing.status,
          completude: briefing.completude,
          payload: (briefing.payload ?? {}) as Record<string, unknown>,
          created_at: briefing.created_at,
          updated_at: briefing.updated_at,
        },
        sections,
        projetoNome,
        autorNome: profile?.nome_completo ?? null,
        autorEmail: profile?.email ?? null,
        sla,
        bimasterUrl: `${origin}/dashboard/briefings/${briefing.id}`,
      };

      const properties = buildPageProperties(blocksInput);
      const allBlocks = buildBriefingBlocks(blocksInput);
      const contentHash = await sha256Hex(JSON.stringify({ properties, allBlocks }));

      // 8. Decide create vs update
      let action: "create" | "update" = "create";
      let pageId = briefing.notion_page_id as string | null;
      let pageUrl = briefing.notion_page_url as string | null;

      if (pageId) {
        // Validate page still exists & is not archived
        const probe = await notion<NotionPage>(token, `/pages/${pageId}`);
        if (!probe.ok || !probe.data || probe.data.archived || probe.data.in_trash) {
          console.log(
            `[notion-export-briefing] linked page ${pageId} gone (${probe.status}) — recreating`,
          );
          pageId = null;
          pageUrl = null;
          await sb
            .from("briefings")
            .update({
              notion_page_id: null,
              notion_page_url: null,
              notion_page_hash: null,
            })
            .eq("id", briefing.id);
        } else {
          // Conflict guard: page edited remotely after our last push, and content actually changed
          const lastPush = briefing.notion_last_push_at as string | null;
          const lastEdited = probe.data.last_edited_time;
          if (
            !force &&
            lastPush &&
            lastEdited &&
            new Date(lastEdited).getTime() > new Date(lastPush).getTime() + 2000 &&
            briefing.notion_page_hash &&
            briefing.notion_page_hash !== contentHash
          ) {
            return new Response(
              JSON.stringify({
                error: "remote_changes_detected",
                message:
                  "A página no Notion foi alterada depois do último envio. Puxe as alterações ou reenvie marcando 'sobrescrever'.",
                page_id: pageId,
                page_url: pageUrl,
                last_edited_time: lastEdited,
                last_push_at: lastPush,
              }),
              { status: 409, headers: { ...cors, "Content-Type": "application/json" } },
            );
          }
          action = "update";
        }
      }

      if (action === "create") {
        // first 100 in create, rest appended
        const firstBatch = allBlocks.slice(0, 100);
        const rest = allBlocks.slice(100);
        const created = await notion<{ id: string; url: string }>(token, "/pages", {
          method: "POST",
          body: JSON.stringify({
            parent: { database_id: dbId },
            properties,
            children: firstBatch,
          }),
        });
        if (!created.ok || !created.data) {
          await sb.from("notion_export_log").insert({
            briefing_id: briefing.id,
            user_id: ctx.userId,
            status: "error",
            error_message: `create page: ${created.status} ${created.errorText ?? ""}`.slice(0, 1000),
          });
          await sb.from("briefing_notion_sync_log").insert({
            briefing_id: briefing.id,
            user_id: ctx.userId,
            direction: "push",
            action: "error",
            status: "error",
            error_message: `create page: ${created.status} ${created.errorText ?? ""}`.slice(0, 1000),
          });
          return new Response(
            JSON.stringify({ error: "page_create_failed", detail: created.errorText }),
            { status: 502, headers: { ...cors, "Content-Type": "application/json" } },
          );
        }
        pageId = created.data.id;
        pageUrl = created.data.url;
        if (rest.length) {
          const r = await appendChildrenInChunks(token, pageId, rest);
          if (!r.ok) console.warn("[notion-export-briefing] append failed", r.errorText);
        }
      } else {
        // UPDATE path: patch properties first
        const propsResp = await notion(token, `/pages/${pageId}`, {
          method: "PATCH",
          body: JSON.stringify({ properties }),
        });
        if (!propsResp.ok) {
          await sb.from("briefing_notion_sync_log").insert({
            briefing_id: briefing.id,
            user_id: ctx.userId,
            direction: "push",
            action: "error",
            status: "error",
            notion_page_id: pageId,
            error_message: `patch props: ${propsResp.status} ${propsResp.errorText ?? ""}`.slice(0, 1000),
          });
          return new Response(
            JSON.stringify({ error: "page_update_failed", detail: propsResp.errorText }),
            { status: 502, headers: { ...cors, "Content-Type": "application/json" } },
          );
        }

        // Replace only the mirror blocks (preserve user's free zone)
        const children = await listAllChildren(token, pageId!);
        const mirrorIds = pickMirrorBlockIds(children);
        if (mirrorIds.length) await deleteBlocks(token, mirrorIds);

        // Re-insert the mirror at the top (Notion appends, but since we cleared the
        // top, the new mirror lands first; the free zone follows naturally).
        // To guarantee ordering we need to: insert mirror, then it sits before any
        // surviving children. Notion API does not support 'insert at index', so we
        // append after the (now-empty) prefix. If free zone existed, it remains at
        // the end relative to the new mirror, which is what we want.
        const r = await appendChildrenInChunks(token, pageId!, allBlocks);
        if (!r.ok) {
          await sb.from("briefing_notion_sync_log").insert({
            briefing_id: briefing.id,
            user_id: ctx.userId,
            direction: "push",
            action: "error",
            status: "error",
            notion_page_id: pageId,
            error_message: `append mirror: ${r.errorText ?? ""}`.slice(0, 1000),
          });
          return new Response(
            JSON.stringify({ error: "page_update_failed", detail: r.errorText }),
            { status: 502, headers: { ...cors, "Content-Type": "application/json" } },
          );
        }
      }

      const nowIso = new Date().toISOString();

      // 9. Log + persist sync state
      await sb.from("notion_export_log").insert({
        briefing_id: briefing.id,
        user_id: ctx.userId,
        status: "success",
        notion_page_id: pageId,
        notion_page_url: pageUrl,
      });
      await sb.from("briefing_notion_sync_log").insert({
        briefing_id: briefing.id,
        user_id: ctx.userId,
        direction: "push",
        action,
        status: "success",
        notion_page_id: pageId,
      });
      await sb
        .from("briefings")
        .update({
          ultimo_export_em: nowIso,
          notion_page_id: pageId,
          notion_page_url: pageUrl,
          notion_last_push_at: nowIso,
          notion_synced_at: nowIso,
          notion_page_hash: contentHash,
        })
        .eq("id", briefing.id);

      return new Response(
        JSON.stringify({
          ok: true,
          action,
          page_id: pageId,
          page_url: pageUrl,
          database_url: dbUrl,
        }),
        { headers: { ...cors, "Content-Type": "application/json" } },
      );
    },
  ),
);
