import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export interface CorporateEvent {
  id: string;
  code: string;
  name: string;
  description: string | null;
  event_type: string;
  event_date: string | null;
  end_date: string | null;
  location: string | null;
  budget_id: string | null;
  budget_amount: number;
  actual_cost: number;
  status: string;
  confidential: boolean;
  responsible_user_id: string | null;
  created_by: string | null;
  approved_by: string | null;
  approved_at: string | null;
  created_at: string;
  updated_at: string;
  budget?: {
    id: string;
    name: string;
    code: string;
    available_amount: number;
  } | null;
  responsible?: {
    id: string;
    nome: string;
  } | null;
  creator?: {
    id: string;
    nome: string;
  } | null;
}

export interface CreateEventInput {
  name: string;
  description?: string;
  event_type: string;
  event_date?: string;
  end_date?: string;
  location?: string;
  budget_id?: string;
  budget_amount?: number;
  confidential?: boolean;
  responsible_user_id?: string;
}

export interface UpdateEventInput extends Partial<CreateEventInput> {
  id: string;
  status?: string;
  approved_by?: string;
  approved_at?: string;
}

export function useCorporateEvents() {
  const queryClient = useQueryClient();

  const eventsQuery = useQuery({
    queryKey: ["corporate-events"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("corporate_events")
        .select(`
          *,
          budget:trade_budgets(id, name, code, available_amount),
          responsible:profiles!corporate_events_responsible_user_id_fkey(id, nome),
          creator:profiles!corporate_events_created_by_fkey(id, nome)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as CorporateEvent[];
    },
  });

  const eventByIdQuery = (id: string) => useQuery({
    queryKey: ["corporate-event", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("corporate_events")
        .select(`
          *,
          budget:trade_budgets(id, name, code, available_amount),
          responsible:profiles!corporate_events_responsible_user_id_fkey(id, nome),
          creator:profiles!corporate_events_created_by_fkey(id, nome)
        `)
        .eq("id", id)
        .single();

      if (error) throw error;
      return data as CorporateEvent;
    },
    enabled: !!id,
  });

  const createEvent = useMutation({
    mutationFn: async (input: CreateEventInput) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Usuário não autenticado");

      const { data, error } = await supabase
        .from("corporate_events")
        .insert({
          code: "", // Will be auto-generated by trigger
          name: input.name,
          description: input.description || null,
          event_type: input.event_type,
          event_date: input.event_date || null,
          end_date: input.end_date || null,
          location: input.location || null,
          budget_id: input.budget_id || null,
          budget_amount: input.budget_amount || 0,
          confidential: input.confidential || false,
          responsible_user_id: input.responsible_user_id || null,
          created_by: user.id,
          status: "draft",
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["corporate-events"] });
      toast.success("Evento criado com sucesso!");
    },
    onError: (error: Error) => {
      toast.error(`Erro ao criar evento: ${error.message}`);
    },
  });

  const updateEvent = useMutation({
    mutationFn: async ({ id, ...input }: UpdateEventInput) => {
      const { data, error } = await supabase
        .from("corporate_events")
        .update(input)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["corporate-events"] });
      queryClient.invalidateQueries({ queryKey: ["corporate-event", variables.id] });
      toast.success("Evento atualizado com sucesso!");
    },
    onError: (error: Error) => {
      toast.error(`Erro ao atualizar evento: ${error.message}`);
    },
  });

  const deleteEvent = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("corporate_events")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["corporate-events"] });
      toast.success("Evento excluído com sucesso!");
    },
    onError: (error: Error) => {
      toast.error(`Erro ao excluir evento: ${error.message}`);
    },
  });

  const approveEvent = useMutation({
    mutationFn: async ({ id, budget_id }: { id: string; budget_id: string }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Usuário não autenticado");

      const { data, error } = await supabase
        .from("corporate_events")
        .update({
          status: "approved",
          budget_id,
          approved_by: user.id,
          approved_at: new Date().toISOString(),
        })
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["corporate-events"] });
      queryClient.invalidateQueries({ queryKey: ["corporate-event", variables.id] });
      queryClient.invalidateQueries({ queryKey: ["pending-corporate-events"] });
      toast.success("Evento aprovado com sucesso!");
    },
    onError: (error: Error) => {
      toast.error(`Erro ao aprovar evento: ${error.message}`);
    },
  });

  const rejectEvent = useMutation({
    mutationFn: async ({ id, observations }: { id: string; observations: string }) => {
      const { data, error } = await supabase
        .from("corporate_events")
        .update({
          status: "rejected",
          description: observations, // Store rejection reason
        })
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["corporate-events"] });
      queryClient.invalidateQueries({ queryKey: ["corporate-event", variables.id] });
      queryClient.invalidateQueries({ queryKey: ["pending-corporate-events"] });
      toast.success("Evento rejeitado.");
    },
    onError: (error: Error) => {
      toast.error(`Erro ao rejeitar evento: ${error.message}`);
    },
  });

  return {
    events: eventsQuery.data ?? [],
    isLoading: eventsQuery.isLoading,
    error: eventsQuery.error,
    refetch: eventsQuery.refetch,
    getEventById: eventByIdQuery,
    createEvent,
    updateEvent,
    deleteEvent,
    approveEvent,
    rejectEvent,
  };
}

export function useEventBudgets() {
  return useQuery({
    queryKey: ["event-budgets"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("trade_budgets")
        .select("id, name, code, available_amount, total_amount, spent_amount")
        .in("status", ["active", "approved"])
        .is("inactivated_at", null)
        .order("name");

      if (error) throw error;
      return data;
    },
  });
}

export function useEventUsers() {
  return useQuery({
    queryKey: ["event-users"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("profiles")
        .select("id, nome, email")
        .order("nome");

      if (error) throw error;
      return data;
    },
  });
}
