
-- GAP 2: Expandir tabela empresas (campos operacionais Omie)
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS codigo_empresa_integracao varchar(20);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS nome_fantasia varchar(60);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS logradouro varchar(6);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS endereco varchar(50);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS endereco_numero varchar(10);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS complemento varchar(60);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS bairro varchar(60);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS cidade varchar(40);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS cep varchar(9);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS codigo_pais varchar(4) DEFAULT '1058';
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS telefone1_ddd varchar(5);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS telefone1_numero varchar(15);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS telefone2_ddd varchar(5);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS telefone2_numero varchar(15);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS fax_ddd varchar(5);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS fax_numero varchar(15);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS email varchar(200);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS website varchar(100);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS cnae varchar(7);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS cnae_municipal varchar(10);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS inscricao_estadual varchar(20);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS inscricao_municipal varchar(20);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS inscricao_suframa varchar(9);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS regime_tributario varchar(1);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS optante_simples_nacional varchar(1);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS contato varchar(100);
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS importado_api boolean DEFAULT false;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS bloqueado boolean DEFAULT false;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- GAP 5: Expandir tabela fornecedores (campos Omie para cadastro completo)
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS nome_fantasia varchar(60);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS logradouro varchar(6);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS endereco_numero varchar(10);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS complemento varchar(60);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS bairro varchar(60);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS cidade varchar(40);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS estado varchar(2);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS cep varchar(9);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS codigo_pais varchar(4) DEFAULT '1058';
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS telefone2 varchar(20);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS fax varchar(20);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS website varchar(100);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS cnae varchar(7);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS inscricao_estadual varchar(20);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS inscricao_municipal varchar(20);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS inscricao_suframa varchar(9);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS regime_tributario varchar(1);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS optante_simples_nacional varchar(1);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS contato varchar(100);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS pessoa_fisica varchar(1) DEFAULT 'N';
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS cpf varchar(14);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS banco varchar(3);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS agencia varchar(10);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS conta_bancaria varchar(20);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS tipo_pix varchar(10);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS chave_pix varchar(100);
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS importado_api boolean DEFAULT false;
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS bloqueado boolean DEFAULT false;
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS inativo boolean DEFAULT false;
ALTER TABLE public.fornecedores ADD COLUMN IF NOT EXISTS observacoes text;
